### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by LarryMays92** [sei-ec-remote/project-4-issues#116]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

Django

### What's the problem you're trying to solve?
trying to create a duration or date field keep getting an error 

### Post any code you think might be relevant (one fenced block per file)
```
start = models.DateField(blank=False, default= '08-15-2022')
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.CannotCoerce: cannot cast type date to time without time zone
LINE 1: ...nt" ALTER COLUMN "duration" TYPE time USING "duration"::time
                                                                 ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/alexisdavenport/se_ice_pops/django-env/maysuniversity/manage.py", line 22, in <module>
    main()
  File "/Users/alexisdavenport/se_ice_pops/django-env/maysuniversity/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 784, in alter_field
    self._alter_field(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 212, in _alter_field
    super()._alter_field(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 1003, in _alter_field
    self.execute(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: cannot cast type date to time without time zone
LINE 1: ...nt" ALTER COLUMN "duration" TYPE time USING "duration"::time
                                                                 ^

### What is your best guess as to the source of the problem?
syntax

### What things have you already tried to solve the problem?
looking up oninternet

**Paste a link to your repository here**
https://github.com/

**Comment by timmshinbone** [comment]
I think it's asking for a timezone argument? I'm not sure. Check out the documentation here: [models.DateField](https://docs.djangoproject.com/en/4.1/ref/models/fields/#django.db.models.DateField)

**Comment by kestler01** [comment]
dates can definitely be tricky, it is looking for a timezone argument becuase Python has a specific way it likes dates
we have docs on that[ here](https://docs.python.org/3/library/datetime.html#datetime-objects)
also consider these fields to change the any default behavior that Django might have [stuff from these docs](https://docs.djangoproject.com/en/4.1/ref/models/fields/#datefield) -(same s timm linked )

**Comment by LarryMays92** [comment]
return executor(sql, params, many, context)
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/alexisdavenport/.local/share/virtualenvs/django-env-DblZDiee/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: cannot cast type date to time without time zone
LINE 1: ...nt" ALTER COLUMN "duration" TYPE time USING "duration"::time
                                                                 ^


i dont even have that field any more i changed it to chars but i kept getting this error when im trying to migrate

**Comment by timmshinbone** [comment]
Did you make new migrations after changing from Date to Char?

**Comment by LarryMays92** [comment]
wont let me m getting an error when i try

**Comment by LarryMays92** [comment]
main_app.Enrollment: (fields.E336) The model is used as an intermediate model by 'main_app.Course.students', but it does not have a foreign key to 'Course' or 'Student'.
main_app.Enrollment: (models.E012) 'unique_together' refers to the nonexistent field 'course'.
main_app.Enrollment: (models.E012) 'unique_together' refers to the nonexistent field 'students'.

**Comment by LarryMays92** [comment]
##############################
# IF I TOUCH THIS FILE I NEED TO MAKE MIGRATIONS THEN MIGRATE
##############################
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=2)
    classification = models.CharField(max_length=8, blank=False) 

    def __str__(self):
        return self.name

class Course(models.Model):
    name = models.CharField(max_length=100)
    duration = models.CharField(max_length=100)
    semester = models.CharField(max_length=1)
    students = models.ManyToManyField(Student, through= 'Enrollment')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE),
    course = models.ForeignKey(Course, on_delete=models.CASCADE),
    start = models.CharField(max_length= 100, default = '2022-08-15'),
    end = models.CharField(max_length= 100, default = '2022-12-15')
    final_grade= models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        unique_together = [['students','course']]

# reference to linking teachers with students and courses and vice versa
#many to many relationship!!

# class Person(models.Model):
#     name = models.CharField(max_length=128)

#     def __str__(self):
#         return self.name

# class Group(models.Model):
#     name = models.CharField(max_length=128)
#     members = models.ManyToManyField(Person, through='Membership')

#     def __str__(self):
#         return self.name

# class Membership(models.Model):
#     person = models.ForeignKey(Person, on_delete=models.CASCADE)
#     group = models.ForeignKey(Group, on_delete=models.CASCADE)
#     date_joined = models.DateField()
#     invite_reason = models.CharField(max_length=64)

**Comment by aishcann** [comment]
resolved
