### ISSUE TITLE
getting an ECONNREFUSED error on start of my server

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/project-4-issues#12]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
mern

### What's the problem you're trying to solve?
trying to sort out the error I'm receiving on starting my api

### Post any code you think might be relevant (one fenced block per file)
```
/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/connection.js:797
  const serverSelectionError = new ServerSelectionError();
                               ^

MongooseServerSelectionError: connect ECONNREFUSED ::1:27017
    at NativeConnection.Connection.openUri (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/connection.js:797:32)
    at /Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/index.js:332:10
    at /Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/index.js:1158:10)
    at Mongoose.connect (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongoose/lib/index.js:331:20)
    at Object.<anonymous> (/Users/bubba/sei/projects/capstone/capstone-api/server.js:31:10)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      'localhost:27017' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: 'localhost', port: 27017 },
        address: 'localhost:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 1103145067,
        lastWriteDate: 0,
        error: MongoNetworkError: connect ECONNREFUSED ::1:27017
            at connectionFailureError (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongodb/lib/cmap/connect.js:293:20)
            at Socket.<anonymous> (/Users/bubba/sei/projects/capstone/capstone-api/node_modules/mongodb/lib/cmap/connect.js:267:22)
            at Object.onceWrapper (node:events:642:26)
            at Socket.emit (node:events:527:28)
            at emitErrorNT (node:internal/streams/destroy:164:8)
            at emitErrorCloseNT (node:internal/streams/destroy:129:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}

```

### What is your best guess as to the source of the problem?
I'm not really sure, I thought I could solve the issue by changing my database url from localhost to the 27017 but it didn't change the problem

### What things have you already tried to solve the problem?
tried referencing past projects to get the correct things in my env but it hasn't changed anything

**Paste a link to your repository here**
[https://github.com/jscodeguy/capstone-api](https://github.com/jscodeguy/capstone-api)

**Comment by DoireannJane** [comment]
Hm did you make any other changes other than the db url?

**Comment by jscodeguy** [comment]
no Ma'am

**Comment by jscodeguy** [comment]
just have my database url and secret in my .env

**Comment by DoireannJane** [comment]
Can we see?

**Comment by timmshinbone** [comment]
Let's take a look together after deploy party

**Comment by jscodeguy** [comment]
understood captain

**Comment by jscodeguy** [comment]
had to change mongodb url in db.js to mongodb://127.0.0.1:27017/${mongooseBaseName}-development from mongodb://localhost/${mongooseBaseName}-development
