### ISSUE TITLE
Attempting to add 'ImageField' for my Events model

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-4-issues#13]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
Django, Python, uncertain about another 

### What's the problem you're trying to solve?
The problem is my model Field for Event needs an Image for the post and when attempting to make migrations it runs an error for the things I added to my 'settings.py' file 

### Post any code you think might be relevant (one fenced block per file)
```py
class Event(models.Model):
    image = models.ImageField(blank = True, upload_to='media'),
    title = models.CharField(max_length=100),
    description = models.CharField(max_length=100)
```
```py
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / 'media'
```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
Traceback (most recent call last):
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/manage.py", line 21, in <module>
    main()
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/TakeItOrLeaveIt/settings.py", line 17, in <module>
    MEDIA_ROOT = BASE_DIR / 'media'
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

### What is your best guess as to the source of the problem?
After googling what I needed to add for my images to be in the model I believe the source of the problem is where I added the MEDIA_ROOT in settings.py but I actually don't know where else to put it as I believe I need it in regards to getting the images to work for the Events model

### What things have you already tried to solve the problem?
Googling lol

**Paste a link to your repository here**
https://github.com/thefrostyausty/CP-TakeItOrLeaveIt
<img width="1713" alt="Screen Shot 2022-04-25 at 11 40 28 AM" src="https://user-images.githubusercontent.com/98559337/165124238-239491e7-f97e-462b-b34b-d1d6b0f49c46.png">
<img width="1811" alt="Screen Shot 2022-04-25 at 11 40 18 AM" src="https://user-images.githubusercontent.com/98559337/165124246-e4f91da0-6584-4577-be7b-918efb8192a8.png">
![Screen Shot 2022-04-25 at 11 40 03 AM](https://user-images.githubusercontent.com/98559337/165124249-1723e292-eea0-49db-aaa7-1e675be50979.png)

**Comment by timmshinbone** [comment]
Hey Austin, I'd recommend away from using the Image field, and just add that aspect of the model as a CharField, that way if a user wants to upload an image, they can just add the image url

**Comment by DoireannJane** [comment]
Hm also... did you previously make migrations?

**Comment by timmshinbone** [comment]
We can take a look together after deploy party this afternoon!

**Comment by thefrostyausty** [comment]
I didn't make any previous migrations this in a sense is the first one. And alrighty, I'll attempt to change the ImageField to CharField. Sounds good to me!

**Comment by DoireannJane** [comment]
Did that change resolve your issue?

**Comment by thefrostyausty** [comment]
It actually has created a new issue where it is basically saying my variable for my model is unexpected? (within the Django Shell)
 
![Screen Shot 2022-04-25 at 2 16 20 PM (2)](https://user-images.githubusercontent.com/98559337/165149552-c5d60b87-d569-4f1f-8364-c6adb1516ced.png)

**Comment by DoireannJane** [comment]
🤔

**Comment by DoireannJane** [comment]
We dropped DB, deleted migrations and recreated and remade migrations.
