### ISSUE TITLE
Need Help with Deployment!

### ISSUE THREAD

**Issue by alysarnau** [sei-ec-remote/project-4-issues#132]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
Deploy our backend to heroku!

### Post any code you think might be relevant (one fenced block per file)
pipfile
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-rest-auth = "*"
django-cors-headers = "*"
python-dotenv = "*"
dj-database-url = "*"
gunicorn = "*"
whitenoise = "*"
django-extensions = "*"
psycopg2-binary = "*"

[dev-packages]

[requires]
python_version = "3.10"
```

pipfile.lock
```
{
    "_meta": {
        "hash": {
            "sha256": "40edbca70a5845a2e452d24e07908cbe264ede8e7007eb517e875ca84f073890"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "asgiref": {
            "hashes": [
                "sha256:1d2880b792ae8757289136f1db2b7b99100ce959b2aa57fd69dab783d05afac4",
                "sha256:4a29362a6acebe09bf1d6640db38c1dc3d9217c68e6f9f6204d72667fc19a424"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==3.5.2"
        },
        "backports.zoneinfo": {
            "hashes": [
                "sha256:17746bd546106fa389c51dbea67c8b7c8f0d14b5526a579ca6ccf5ed72c526cf",
                "sha256:1b13e654a55cd45672cb54ed12148cd33628f672548f373963b0bff67b217328",
                "sha256:1c5742112073a563c81f786e77514969acb58649bcdf6cdf0b4ed31a348d4546",
                "sha256:4a0f800587060bf8880f954dbef70de6c11bbe59c673c3d818921f042f9954a6",
                "sha256:5c144945a7752ca544b4b78c8c41544cdfaf9786f25fe5ffb10e838e19a27570",
                "sha256:7b0a64cda4145548fed9efc10322770f929b944ce5cee6c0dfe0c87bf4c0c8c9",
                "sha256:8439c030a11780786a2002261569bdf362264f605dfa4d65090b64b05c9f79a7",
                "sha256:8961c0f32cd0336fb8e8ead11a1f8cd99ec07145ec2931122faaac1c8f7fd987",
                "sha256:89a48c0d158a3cc3f654da4c2de1ceba85263fafb861b98b59040a5086259722",
                "sha256:a76b38c52400b762e48131494ba26be363491ac4f9a04c1b7e92483d169f6582",
                "sha256:da6013fd84a690242c310d77ddb8441a559e9cb3d3d59ebac9aca1a57b2e18bc",
                "sha256:e55b384612d93be96506932a786bbcde5a2db7a9e6a4bb4bffe8b733f5b9036b",
                "sha256:e81b76cace8eda1fca50e345242ba977f9be6ae3945af8d46326d776b4cf78d1",
                "sha256:e8236383a20872c0cdf5a62b554b27538db7fa1bbec52429d8d106effbaeca08",
                "sha256:f04e857b59d9d1ccc39ce2da1021d196e47234873820cbeaad210724b1ee28ac",
                "sha256:fadbfe37f74051d024037f223b8e001611eac868b5c5b06144ef4d8b799862f2"
            ],
            "markers": "python_version < '3.9'",
            "version": "==0.2.1"
        },
        "dj-database-url": {
            "hashes": [
                "sha256:ccf3e8718f75ddd147a1e212fca88eecdaa721759ee48e38b485481c77bca3dc",
                "sha256:cd354a3b7a9136d78d64c17b2aec369e2ae5616fbca6bfbe435ef15bb372ce39"
            ],
            "index": "pypi",
            "version": "==1.0.0"
        },
        "django": {
            "hashes": [
                "sha256:031ccb717782f6af83a0063a1957686e87cb4581ea61b47b3e9addf60687989a",
                "sha256:032f8a6fc7cf05ccd1214e4a2e21dfcd6a23b9d575c6573cacc8c67828dbe642"
            ],
            "markers": "python_version >= '3.8'",
            "version": "==4.1"
        },
        "django-cors-headers": {
            "hashes": [
                "sha256:37e42883b5f1f2295df6b4bba96eb2417a14a03270cb24b2a07f021cd4487cf4",
                "sha256:f9dc6b4e3f611c3199700b3e5f3398c28757dcd559c2f82932687f3d0443cfdf"
            ],
            "index": "pypi",
            "version": "==3.13.0"
        },
        "django-extensions": {
            "hashes": [
                "sha256:4c234a7236e9e41c17d9036f6dae7a3a9b212527105b8a0d24b2459b267825f0",
                "sha256:7dc7cd1da50d83b76447a58f5d7e5c8e6cd83f21e9b7e5f97e6b644f4d4e21a6"
            ],
            "index": "pypi",
            "version": "==3.2.0"
        },
        "django-rest-auth": {
            "hashes": [
                "sha256:f11e12175dafeed772f50d740d22caeab27e99a3caca24ec65e66a8d6de16571"
            ],
            "index": "pypi",
            "version": "==0.9.5"
        },
        "djangorestframework": {
            "hashes": [
                "sha256:0c33407ce23acc68eca2a6e46424b008c9c02eceb8cf18581921d0092bc1f2ee",
                "sha256:24c4bf58ed7e85d1fe4ba250ab2da926d263cd57d64b03e8dcef0ac683f8b1aa"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==3.13.1"
        },
        "gunicorn": {
            "hashes": [
                "sha256:9dcc4547dbb1cb284accfb15ab5667a0e5d1881cc443e0677b4882a4067a807e",
                "sha256:e0a968b5ba15f8a328fdfd7ab1fcb5af4470c28aaf7e55df02a99bc13138e6e8"
            ],
            "index": "pypi",
            "version": "==20.1.0"
        },
        "psycopg2-binary": {
            "hashes": [
                "sha256:01310cf4cf26db9aea5158c217caa92d291f0500051a6469ac52166e1a16f5b7",
                "sha256:083a55275f09a62b8ca4902dd11f4b33075b743cf0d360419e2051a8a5d5ff76",
                "sha256:090f3348c0ab2cceb6dfbe6bf721ef61262ddf518cd6cc6ecc7d334996d64efa",
                "sha256:0a29729145aaaf1ad8bafe663131890e2111f13416b60e460dae0a96af5905c9",
                "sha256:0c9d5450c566c80c396b7402895c4369a410cab5a82707b11aee1e624da7d004",
                "sha256:10bb90fb4d523a2aa67773d4ff2b833ec00857f5912bafcfd5f5414e45280fb1",
                "sha256:12b11322ea00ad8db8c46f18b7dfc47ae215e4df55b46c67a94b4effbaec7094",
                "sha256:152f09f57417b831418304c7f30d727dc83a12761627bb826951692cc6491e57",
                "sha256:15803fa813ea05bef089fa78835118b5434204f3a17cb9f1e5dbfd0b9deea5af",
                "sha256:15c4e4cfa45f5a60599d9cec5f46cd7b1b29d86a6390ec23e8eebaae84e64554",
                "sha256:183a517a3a63503f70f808b58bfbf962f23d73b6dccddae5aa56152ef2bcb232",
                "sha256:1f14c8b0942714eb3c74e1e71700cbbcb415acbc311c730370e70c578a44a25c",
                "sha256:1f6b813106a3abdf7b03640d36e24669234120c72e91d5cbaeb87c5f7c36c65b",
                "sha256:280b0bb5cbfe8039205c7981cceb006156a675362a00fe29b16fbc264e242834",
                "sha256:2d872e3c9d5d075a2e104540965a1cf898b52274a5923936e5bfddb58c59c7c2",
                "sha256:2f9ffd643bc7349eeb664eba8864d9e01f057880f510e4681ba40a6532f93c71",
                "sha256:3303f8807f342641851578ee7ed1f3efc9802d00a6f83c101d21c608cb864460",
                "sha256:35168209c9d51b145e459e05c31a9eaeffa9a6b0fd61689b48e07464ffd1a83e",
                "sha256:3a79d622f5206d695d7824cbf609a4f5b88ea6d6dab5f7c147fc6d333a8787e4",
                "sha256:404224e5fef3b193f892abdbf8961ce20e0b6642886cfe1fe1923f41aaa75c9d",
                "sha256:46f0e0a6b5fa5851bbd9ab1bc805eef362d3a230fbdfbc209f4a236d0a7a990d",
                "sha256:47133f3f872faf28c1e87d4357220e809dfd3fa7c64295a4a148bcd1e6e34ec9",
                "sha256:526ea0378246d9b080148f2d6681229f4b5964543c170dd10bf4faaab6e0d27f",
                "sha256:53293533fcbb94c202b7c800a12c873cfe24599656b341f56e71dd2b557be063",
                "sha256:539b28661b71da7c0e428692438efbcd048ca21ea81af618d845e06ebfd29478",
                "sha256:57804fc02ca3ce0dbfbef35c4b3a4a774da66d66ea20f4bda601294ad2ea6092",
                "sha256:63638d875be8c2784cfc952c9ac34e2b50e43f9f0a0660b65e2a87d656b3116c",
                "sha256:6472a178e291b59e7f16ab49ec8b4f3bdada0a879c68d3817ff0963e722a82ce",
                "sha256:68641a34023d306be959101b345732360fc2ea4938982309b786f7be1b43a4a1",
                "sha256:6e82d38390a03da28c7985b394ec3f56873174e2c88130e6966cb1c946508e65",
                "sha256:761df5313dc15da1502b21453642d7599d26be88bff659382f8f9747c7ebea4e",
                "sha256:7af0dd86ddb2f8af5da57a976d27cd2cd15510518d582b478fbb2292428710b4",
                "sha256:7b1e9b80afca7b7a386ef087db614faebbf8839b7f4db5eb107d0f1a53225029",
                "sha256:874a52ecab70af13e899f7847b3e074eeb16ebac5615665db33bce8a1009cf33",
                "sha256:887dd9aac71765ac0d0bac1d0d4b4f2c99d5f5c1382d8b770404f0f3d0ce8a39",
                "sha256:8b344adbb9a862de0c635f4f0425b7958bf5a4b927c8594e6e8d261775796d53",
                "sha256:8fc53f9af09426a61db9ba357865c77f26076d48669f2e1bb24d85a22fb52307",
                "sha256:91920527dea30175cc02a1099f331aa8c1ba39bf8b7762b7b56cbf54bc5cce42",
                "sha256:93cd1967a18aa0edd4b95b1dfd554cf15af657cb606280996d393dadc88c3c35",
                "sha256:99485cab9ba0fa9b84f1f9e1fef106f44a46ef6afdeec8885e0b88d0772b49e8",
                "sha256:9d29409b625a143649d03d0fd7b57e4b92e0ecad9726ba682244b73be91d2fdb",
                "sha256:a29b3ca4ec9defec6d42bf5feb36bb5817ba3c0230dd83b4edf4bf02684cd0ae",
                "sha256:a9e1f75f96ea388fbcef36c70640c4efbe4650658f3d6a2967b4cc70e907352e",
                "sha256:accfe7e982411da3178ec690baaceaad3c278652998b2c45828aaac66cd8285f",
                "sha256:adf20d9a67e0b6393eac162eb81fb10bc9130a80540f4df7e7355c2dd4af9fba",
                "sha256:af9813db73395fb1fc211bac696faea4ca9ef53f32dc0cfa27e4e7cf766dcf24",
                "sha256:b1c8068513f5b158cf7e29c43a77eb34b407db29aca749d3eb9293ee0d3103ca",
                "sha256:bda845b664bb6c91446ca9609fc69f7db6c334ec5e4adc87571c34e4f47b7ddb",
                "sha256:c381bda330ddf2fccbafab789d83ebc6c53db126e4383e73794c74eedce855ef",
                "sha256:c3ae8e75eb7160851e59adc77b3a19a976e50622e44fd4fd47b8b18208189d42",
                "sha256:d1c1b569ecafe3a69380a94e6ae09a4789bbb23666f3d3a08d06bbd2451f5ef1",
                "sha256:def68d7c21984b0f8218e8a15d514f714d96904265164f75f8d3a70f9c295667",
                "sha256:dffc08ca91c9ac09008870c9eb77b00a46b3378719584059c034b8945e26b272",
                "sha256:e3699852e22aa68c10de06524a3721ade969abf382da95884e6a10ff798f9281",
                "sha256:e847774f8ffd5b398a75bc1c18fbb56564cda3d629fe68fd81971fece2d3c67e",
                "sha256:ffb7a888a047696e7f8240d649b43fb3644f14f0ee229077e7f6b9f9081635bd"
            ],
            "index": "pypi",
            "version": "==2.9.3"
        },
        "python-dotenv": {
            "hashes": [
                "sha256:b7e3b04a59693c42c36f9ab1cc2acc46fa5df8c78e178fc33a8d4cd05c8d498f",
                "sha256:d92a187be61fe482e4fd675b6d52200e7be63a12b724abbf931a40ce4fa92938"
            ],
            "index": "pypi",
            "version": "==0.20.0"
        },
        "pytz": {
            "hashes": [
                "sha256:220f481bdafa09c3955dfbdddb7b57780e9a94f5127e35456a48589b9e0c0197",
                "sha256:cea221417204f2d1a2aa03ddae3e867921971d0d76f14d87abb4414415bbdcf5"
            ],
            "version": "==2022.2.1"
        },
        "setuptools": {
            "hashes": [
                "sha256:2e24e0bec025f035a2e72cdd1961119f557d78ad331bb00ff82efb2ab8da8e82",
                "sha256:7732871f4f7fa58fb6bdcaeadb0161b2bd046c85905dbaa066bdcbcc81953b57"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==65.3.0"
        },
        "six": {
            "hashes": [
                "sha256:1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926",
                "sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.16.0"
        },
        "sqlparse": {
            "hashes": [
                "sha256:0c00730c74263a94e5a9919ade150dfc3b19c574389985446148402998287dae",
                "sha256:48719e356bb8b42991bdbb1e8b83223757b93789c00910a616a071910ca4a64d"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==0.4.2"
        },
        "whitenoise": {
            "hashes": [
                "sha256:8e9c600a5c18bd17655ef668ad55b5edf6c24ce9bdca5bf607649ca4b1e8e2c2",
                "sha256:8fa943c6d4cd9e27673b70c21a07b0aa120873901e099cd46cab40f7cc96d567"
            ],
            "index": "pypi",
            "version": "==6.2.0"
        }
    },
    "develop": {}
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
Traceback (most recent call last):
2022-08-25T19:57:02.055096+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
2022-08-25T19:57:02.055209+00:00 app[release.4299]: self.connect()
2022-08-25T19:57:02.055232+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.055281+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.055282+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
2022-08-25T19:57:02.055421+00:00 app[release.4299]: self.connection = self.get_new_connection(conn_params)
2022-08-25T19:57:02.055422+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.055552+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.055552+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
2022-08-25T19:57:02.055590+00:00 app[release.4299]: connection = Database.connect(**conn_params)
2022-08-25T19:57:02.055590+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
2022-08-25T19:57:02.055705+00:00 app[release.4299]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2022-08-25T19:57:02.055706+00:00 app[release.4299]: psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2022-08-25T19:57:02.055706+00:00 app[release.4299]: Is the server running locally and accepting connections on that socket?
2022-08-25T19:57:02.055706+00:00 app[release.4299]: 
2022-08-25T19:57:02.055707+00:00 app[release.4299]: 
2022-08-25T19:57:02.055707+00:00 app[release.4299]: The above exception was the direct cause of the following exception:
2022-08-25T19:57:02.055707+00:00 app[release.4299]: 
2022-08-25T19:57:02.055707+00:00 app[release.4299]: Traceback (most recent call last):
2022-08-25T19:57:02.055718+00:00 app[release.4299]: File "/app/manage.py", line 21, in <module>
2022-08-25T19:57:02.055865+00:00 app[release.4299]: main()
2022-08-25T19:57:02.055868+00:00 app[release.4299]: File "/app/manage.py", line 17, in main
2022-08-25T19:57:02.055891+00:00 app[release.4299]: execute_from_command_line(sys.argv)
2022-08-25T19:57:02.056372+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
2022-08-25T19:57:02.056382+00:00 app[release.4299]: utility.execute()
2022-08-25T19:57:02.056383+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
2022-08-25T19:57:02.056384+00:00 app[release.4299]: self.fetch_command(subcommand).run_from_argv(self.argv)
2022-08-25T19:57:02.056385+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
2022-08-25T19:57:02.056385+00:00 app[release.4299]: self.execute(*args, **cmd_options)
2022-08-25T19:57:02.056386+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
2022-08-25T19:57:02.056449+00:00 app[release.4299]: output = self.handle(*args, **options)
2022-08-25T19:57:02.056484+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
2022-08-25T19:57:02.056531+00:00 app[release.4299]: res = handle_func(*args, **kwargs)
2022-08-25T19:57:02.056558+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 114, in handle
2022-08-25T19:57:02.056638+00:00 app[release.4299]: executor = MigrationExecutor(connection, self.migration_progress_callback)
2022-08-25T19:57:02.056639+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
2022-08-25T19:57:02.056695+00:00 app[release.4299]: self.loader = MigrationLoader(self.connection)
2022-08-25T19:57:02.056714+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
2022-08-25T19:57:02.056784+00:00 app[release.4299]: self.build_graph()
2022-08-25T19:57:02.056819+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
2022-08-25T19:57:02.056881+00:00 app[release.4299]: self.applied_migrations = recorder.applied_migrations()
2022-08-25T19:57:02.056898+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
2022-08-25T19:57:02.057012+00:00 app[release.4299]: if self.has_table():
2022-08-25T19:57:02.057013+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
2022-08-25T19:57:02.057080+00:00 app[release.4299]: with self.connection.cursor() as cursor:
2022-08-25T19:57:02.057112+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.057169+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.057169+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
2022-08-25T19:57:02.057313+00:00 app[release.4299]: return self._cursor()
2022-08-25T19:57:02.057354+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
2022-08-25T19:57:02.057394+00:00 app[release.4299]: self.ensure_connection()
2022-08-25T19:57:02.057395+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.057425+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.057426+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
2022-08-25T19:57:02.057574+00:00 app[release.4299]: with self.wrap_database_errors:
2022-08-25T19:57:02.057618+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
2022-08-25T19:57:02.057645+00:00 app[release.4299]: raise dj_exc_value.with_traceback(traceback) from exc_value
2022-08-25T19:57:02.057646+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
2022-08-25T19:57:02.057756+00:00 app[release.4299]: self.connect()
2022-08-25T19:57:02.057756+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.057823+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.057823+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
2022-08-25T19:57:02.057979+00:00 app[release.4299]: self.connection = self.get_new_connection(conn_params)
2022-08-25T19:57:02.057979+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
2022-08-25T19:57:02.058087+00:00 app[release.4299]: return func(*args, **kwargs)
2022-08-25T19:57:02.058087+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 215, in get_new_connection
2022-08-25T19:57:02.058193+00:00 app[release.4299]: connection = Database.connect(**conn_params)
2022-08-25T19:57:02.058220+00:00 app[release.4299]: File "/app/.heroku/python/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
2022-08-25T19:57:02.058261+00:00 app[release.4299]: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2022-08-25T19:57:02.058274+00:00 app[release.4299]: django.db.utils.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2022-08-25T19:57:02.058275+00:00 app[release.4299]: Is the server running locally and accepting connections on that socket?
2022-08-25T19:57:02.058291+00:00 app[release.4299]: 
2022-08-25T19:57:02.273886+00:00 heroku[release.4299]: Process exited with status 1
2022-08-25T19:57:02.328868+00:00 heroku[release.4299]: State changed from up to complete
2022-08-25T19:57:03.974652+00:00 app[api]: Release v14 command failed by user alice.g.cooper@gmail.com
2022-08-25T19:57:19.617577+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=secret-caverns-60922.herokuapp.com request_id=586e132e-b028-4daa-a8f6-3fa643e3349a fwd="73.159.226.139" dyno= connect= service= status=503 bytes= protocol=https
2022-08-25T19:57:19.862657+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/favicon.ico" host=secret-caverns-60922.herokuapp.com request_id=1de48354-e996-48ea-8491-5844b7a974b2 fwd="73.159.226.139" dyno= connect= service= status=503 bytes= protocol=https

```

### What is your best guess as to the source of the problem?
Honestly no idea

### What things have you already tried to solve the problem?
I made sure that the pipfile included both django-extensions and psycopg2-binary.

**Paste a link to your repository here**
https://github.com/alysvolatile/my-junimo-api

**Comment by kestler01** [comment]
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
2022-08-25T19:57:02.055706+00:00 app[release.4299]: Is the server running locally and accepting connections on that socket?

looks like you need to hook up your psql solution before the server will work

**Comment by kestler01** [comment]
did we go through the steps 10-14 of the https://git.generalassemb.ly/sei-ec-remote/django-heroku-deployment-guide ?

**Comment by alysarnau** [comment]
I have! See my multiple heroku_spotgresURLs :sob:

```
alys@Alys-Volatile:~/sei_ice_pops/projects/StardewValleyHelper/myJunimoAPI$ heroku addons:create heroku-postgresql:hobby-dev
Creating heroku-postgresql:hobby-dev on ⬢ secret-caverns-60922... free
Database has been created and is available
 ! This database is empty. If upgrading, you can transfer
 ! data from another database with pg:copy
Created postgresql-round-55090 as HEROKU_POSTGRESQL_JADE_URL
Use heroku addons:docs heroku-postgresql to view documentation
(myJunimoAPI) alys@Alys-Volatile:~/sei_ice_pops/projects/StardewValleyHelper/myJunimoAPI$ heroku config
=== secret-caverns-60922 Config Vars
CLIENT_ORIGIN:                https://github.com/alysvolatile
DATABASE_URL:                 postgres://nrswplbmlecvhy:3977c488ea8d8eca6bdc06d67ae9756fc2d4eec68b7d4e4a67adefb6956c18da@ec2-44-208-88-195.compute-1.amazonaws.com:5432/d1b3g7qa72mdgl
DISABLE_COLLECTSTATIC:        0
HEROKU_POSTGRESQL_JADE_URL:   postgres://kgdqcatdiyrlvc:8f0767f53840eea7fc26875c99e451985d340639bff7f35813e45a0d7b52c80b@ec2-34-227-135-211.compute-1.amazonaws.com:5432/dahqf1r77mdopb
HEROKU_POSTGRESQL_ORANGE_URL: postgres://ktmsrbdiqtvuzy:c21ad948d50e4b84d77e329965e044d3ee64c9619119c5fd95ced4d0fc1d31e6@ec2-44-205-112-253.compute-1.amazonaws.com:5432/d9vitjcj12l9f1
HEROKU_POSTGRESQL_PURPLE_URL: postgres://meldnmbkfpxpzb:18c8d978235ab8917fa73b45e15a898ff6f59cf442e5655021461822538e3b85@ec2-3-225-110-188.compute-1.amazonaws.com:5432/d5qfm0ah35uihj
SECRET:                       REDACTED
```

**Comment by kestler01** [comment]
client origin should be the url of your deployed front end, typically looks like `https://my-username.github.io`
That shouldn't be the source of this issue tho. We will touch base in the AM tomorrow

**Comment by alysarnau** [comment]
Ah, I see! Glad to know it's user error. Here's the spicy take though - we are NOT deploying the front end quite yet, this is just so we can deploy the back end and go from there. in that case, would client_origin be something like `http://127.0.0.1:8000/`?

**Comment by timmshinbone** [comment]
^That client origin is for a react app deployed to GH-pages(which is what Andrew's class did, but not what this class does)

**Comment by timmshinbone** [comment]
You don't need to set client origin yet until your react app is deployed

**Comment by timmshinbone** [comment]
This is what heroku recommends for H14 error code:
https://devcenter.heroku.com/articles/error-codes#h14-no-web-dynos-running

Not sure if that's the problem though

**Comment by timmshinbone** [comment]
Any updates on this?

**Comment by alysarnau** [comment]
No - I did the troubleshooting for H14 but still not working. Still need assistance on this.

**Comment by alysarnau** [comment]
Resolution to date: try deploying NOT on an ubuntu machine. I'll try on Sunday!

**Comment by alysarnau** [comment]
Still not working, honestly I'm tearing my hair out. We tried on Linux, Mac, and Windows, still getting the same error. Possibly something in the settings.py? I would appreciate help in this, alternately I will pay someone to deploy this for me because I am losing my mind.

**Comment by alysarnau** [comment]
I think something is getting mixed up due to boilerplate here - does anyone have just generic postgres database connection template we can try and use manually?

**Comment by alysarnau** [comment]
WE DEPLOYED IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ANDREW IS A CODING GENIUS!!!!!!!!!
