### ISSUE TITLE
Issue sending creating 

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-4-issues#139]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I am having a hard time getting the database to send us the favorites list, or maybe saving the data. Could I meet with someone on zoom for a quick orienting because I am at a lose for what to do next. 

### Post any code you think might be relevant (one fenced block per file)
```
```

### What things have you already tried to solve the problem?

**Paste a link to your repository here**

**Comment by mattkeane-ga** [comment]
What have you tried? What happened?

**Comment by christian-the-brewer** [comment]
I have tried a bunch of different iterations of the back end add to favorites routes and saving the data from the api. Currently I am getting this error on my latest attempt in my back end terminal:
```
Fri Aug 26 2022 15:12:21 GMT-0400 (Eastern Daylight Time)
POST /favorites/add
body {"user":{"_id":"6306d42c655056bb8bab551d","email":"p@p.p","userName":"p","createdAt":"2022-08-25T01:45:16.046Z","updatedAt":"2022-08-26T18:50:24.589Z","__v":0,"token":"4eb972d73c50d7cc3989bc811bea8055"},"content":{"contentId":755566,"title":"Day Shift","poster_path":"/bI7lGR5HuYlENlp11brKUAaPHuO.jpg","release_date":"2022-08-10","vote_average":6.794,"overview":"An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.","tagline":"Some jobs really go for the throat.","genres":[{"id":28,"name":"Action"},{"id":14,"name":"Fantasy"},{"id":27,"name":"Horror"},{"id":35,"name":"Comedy"}],"runtime":113,"type":"movie"}}

============================

/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema/string.js:603
    throw new CastError('string', value, this.path, null, this);
          ^

CastError: Cast to string failed for value "{
  contentId: 755566,
  title: 'Day Shift',
  poster_path: '/bI7lGR5HuYlENlp11brKUAaPHuO.jpg',
  release_date: '2022-08-10',
  vote_average: 6.794,
  overview: "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
  tagline: 'Some jobs really go for the throat.',
  genres: [
    { id: 28, name: 'Action' },
    { id: 14, name: 'Fantasy' },
    { id: 27, name: 'Horror' },
    { id: 35, name: 'Comedy' }
  ],
  runtime: 113,
  type: 'movie'
}" (type Object) at path "content"
    at SchemaString.cast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema/string.js:603:11)
    at SchemaString.SchemaType.applySetters (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schematype.js:1135:12)
    at Proxy._cast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:245:43)
    at Proxy._mapCast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:258:17)
    at Arguments.map (<anonymous>)
    at Proxy.push (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:654:21)
    at /home/gene/sei/projects/capstone_project/streamgenie-backend_api/app/routes/favorites_routes.js:77:31
    at /home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/model.js:4942:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  stringValue: '"{\n' +
    '  contentId: 755566,\n' +
    "  title: 'Day Shift',\n" +
    "  poster_path: '/bI7lGR5HuYlENlp11brKUAaPHuO.jpg',\n" +
    "  release_date: '2022-08-10',\n" +
    '  vote_average: 6.794,\n' +
    `  overview: "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",\n` +
    "  tagline: 'Some jobs really go for the throat.',\n" +
    '  genres: [\n' +
    "    { id: 28, name: 'Action' },\n" +
    "    { id: 14, name: 'Fantasy' },\n" +
    "    { id: 27, name: 'Horror' },\n" +
    "    { id: 35, name: 'Comedy' }\n" +
    '  ],\n' +
    '  runtime: 113,\n' +
    "  type: 'movie'\n" +
    '}"',
  messageFormat: undefined,
  kind: 'string',
  value: {
    contentId: 755566,
    title: 'Day Shift',
    poster_path: '/bI7lGR5HuYlENlp11brKUAaPHuO.jpg',
    release_date: '2022-08-10',
    vote_average: 6.794,
    overview: "An LA vampire hunter has a week to come up with the cash to pay for his kid's tuition and braces. Trying to make a living these days just might kill him.",
    tagline: 'Some jobs really go for the throat.',
    genres: [
      { id: 28, name: 'Action' },
      { id: 14, name: 'Fantasy' },
      { id: 27, name: 'Horror' },
      { id: 35, name: 'Comedy' }
    ],
    runtime: 113,
    type: 'movie'
  },
  path: 'content',
  reason: null,
  valueType: 'Object'
}
[nodemon] app crashed - waiting for file changes before starting...

```

my add to favorites route is currently this:
```js
router.post('/favorites/add', requireToken, async (req, res, nexcart) => {
    Favorites.findOne({ owner: req.user.id }, async function (error, favorites) {
        if (favorites) {
            // favorites.content.push(req.body.content)
            favorites.content.push(req.body.content)
            await favorites.save()
            console.log("movie:", req.body.content)
            console.log("added to existing favorites list", favorites)
            console.log('favorites.content:', favorites.content)
        } else {
            const newFavorites = new Favorites()
            newFavorites.owner = req.user.id
            newFavorites.content.title = req.body.content.title

            // newFavorites.content.push(req.body.content)
            await newFavorites.save()
            console.log("movie:", req.body.content)
            console.log("create new favorites list with :", favorites)
            console.log('favorites.content:', favorites.content)
        }
    })

})
```

I am checking to see if the user has a favorites list, and if they do I am trying too push the current movie into it. If not, I want to make a new list and then push the content into it

**Comment by mattkeane-ga** [comment]
What does your `Favorites` model look like?

**Comment by christian-the-brewer** [comment]
making a new user and trying to hit that second route I get:
```
movie: {
  contentId: 616037,
  title: 'Thor: Love and Thunder',
  poster_path: '/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg',
  release_date: '2022-07-06',
  vote_average: 6.779,
  overview: 'After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor Odinson enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Relatively Mighty Girl Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher’s vengeance and stop him before it’s too late.',
  tagline: 'The one is not the only.',
  genres: [
    { id: 28, name: 'Action' },
    { id: 12, name: 'Adventure' },
    { id: 14, name: 'Fantasy' }
  ],
  runtime: 119,
  type: 'movie'
}
create new favorites list : {
  content: [],
  _id: new ObjectId("63091cf764e2dd5e22793624"),
  owner: new ObjectId("63091cf464e2dd5e2279361e"),
  createdAt: 2022-08-26T19:20:23.654Z,
  updatedAt: 2022-08-26T19:20:23.654Z,
  __v: 0
}
newfavorites.content: [ title: 'Thor: Love and Thunder' ]

```
so it seems to be adding something! but when I check my consolelog for my front end and see what I am sending over to there for favorites I get an array with length 0

**Comment by christian-the-brewer** [comment]
my favorites model:
```js
const mongoose = require('mongoose')

const favoritesSchema = new mongoose.Schema(
    {
        content: [
            {
                contentId: Number,
                title: String,
                poster_path: String,
                release_date: String,
                vote_average: Number,
                overview: String,
                tagline: String,
                genre: [String],
                runtime: Number,
                number_of_seasons: Number,
                type: String

            }
        ],
        owner: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
        }
    },

    {

        timestamps: true
    }
)

module.exports = mongoose.model('Favorites', favoritesSchema)
```

**Comment by mattkeane-ga** [comment]
What datatype is the `content` field on your `Favorites` model?

**Comment by christian-the-brewer** [comment]
I dont think I have one specified. I tried adding a data type to it but I couldnt figure out how to do it with the array and object in it

**Comment by mattkeane-ga** [comment]
Are you sure? What datatype is this?
```js
[
            {
                contentId: Number,
                title: String,
                poster_path: String,
                release_date: String,
                vote_average: Number,
                overview: String,
                tagline: String,
                genre: [String],
                runtime: Number,
                number_of_seasons: Number,
                type: String

            }
]
```
Look at the square brackets...

**Comment by christian-the-brewer** [comment]
Oh I understand the question now, it is an array!

**Comment by mattkeane-ga** [comment]
Yes now think about this line:
```js
newFavorites.content.title = req.body.content.title
```
Is that what you intend to be doing?

**Comment by christian-the-brewer** [comment]
ah I see. I originally was pushing the object in like the first part of that route with that commented out newFavorites.content.push(req.body.content) , but when that wasnt working I wrote that but yes it obviously will not work

**Comment by mattkeane-ga** [comment]
The only other thing that jumps out at me is that it looks like your model has `genre` as an array of strings, but your api data has `genres` as an array of objects.

**Comment by christian-the-brewer** [comment]
maybe that was the original error I was getting about type error. I couldnt figure out where that was coming from so I strayed further and further from my original route that now looks like it was closer to what it needs to be. I change the model to be an array of objects

**Comment by mattkeane-ga** [comment]
Does it work now? Is there a different error?

**Comment by christian-the-brewer** [comment]
I get my original error again:
```
/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema/string.js:603
    throw new CastError('string', value, this.path, null, this);
          ^

CastError: Cast to string failed for value "{
  contentId: 610150,
  title: 'Dragon Ball Super: Super Hero',
  poster_path: '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg',
  release_date: '2022-06-11',
  vote_average: 7.44,
  overview: 'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',
  tagline: 'A super awakening and calamity is born.',
  genres: [
    { id: 16, name: 'Animation' },
    { id: 878, name: 'Science Fiction' },
    { id: 28, name: 'Action' }
  ],
  runtime: 99,
  type: 'movie'
}" (type Object) at path "content"
    at SchemaString.cast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema/string.js:603:11)
    at SchemaString.SchemaType.applySetters (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schematype.js:1135:12)
    at Proxy._cast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:245:43)
    at Proxy._mapCast (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:258:17)
    at Arguments.map (<anonymous>)
    at Proxy.push (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/types/array/methods/index.js:654:21)
    at /home/gene/sei/projects/capstone_project/streamgenie-backend_api/app/routes/favorites_routes.js:94:34
    at /home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/model.js:4942:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  stringValue: '"{\n' +
    '  contentId: 610150,\n' +
    "  title: 'Dragon Ball Super: Super Hero',\n" +
    "  poster_path: '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg',\n" +
    "  release_date: '2022-06-11',\n" +
    '  vote_average: 7.44,\n' +
    "  overview: 'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',\n" +
    "  tagline: 'A super awakening and calamity is born.',\n" +
    '  genres: [\n' +
    "    { id: 16, name: 'Animation' },\n" +
    "    { id: 878, name: 'Science Fiction' },\n" +
    "    { id: 28, name: 'Action' }\n" +
    '  ],\n' +
    '  runtime: 99,\n' +
    "  type: 'movie'\n" +
    '}"',
  messageFormat: undefined,
  kind: 'string',
  value: {
    contentId: 610150,
    title: 'Dragon Ball Super: Super Hero',
    poster_path: '/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg',
    release_date: '2022-06-11',
    vote_average: 7.44,
    overview: 'The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.',
    tagline: 'A super awakening and calamity is born.',
    genres: [
      { id: 16, name: 'Animation' },
      { id: 878, name: 'Science Fiction' },
      { id: 28, name: 'Action' }
    ],
    runtime: 99,
    type: 'movie'
  },
  path: 'content',
  reason: null,
  valueType: 'Object'
```

**Comment by christian-the-brewer** [comment]
could it be those line breaks in the object? I have to check to see why are coming in

**Comment by christian-the-brewer** [comment]
I do not see those in the api data I get back in my browser. so I am not sure where it is being added to the data

**Comment by mattkeane-ga** [comment]
Oh! With a little research, [I found this on StackOverflow](https://stackoverflow.com/questions/33846939/mongoose-schema-error-cast-to-string-failed-for-value-when-pushing-object-to). Essentially, since your object has a `type` property on it, Mongoose interprets that as meaning you want that to indicate the type of data that should go into the array. Instead of thinking that you mean an object with a type property with the type String, it thinks you mean the whole thing should be a string. The workaround is to change the options in your schema to this:
```js
{
    timestamps: true,
    typeKey: '$type'
}
```

**Comment by christian-the-brewer** [comment]
I found that a few days ago and tried that but It crashes my app. I think it might be old syntax?

**Comment by mattkeane-ga** [comment]
What error do you get when you try that?

**Comment by christian-the-brewer** [comment]
```
/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:1066
    throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
    ^

TypeError: Invalid schema configuration: `User` is not a valid type at path `owner.ref`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:1066:11)
    at Schema.path (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:710:27)
    at Schema.add (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:527:12)
    at Schema.add (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:539:12)
    at new Schema (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/node_modules/mongoose/lib/schema.js:128:10)
    at Object.<anonymous> (/home/gene/sei/projects/capstone_project/streamgenie-backend_api/app/models/favorites.js:3:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by mattkeane-ga** [comment]
When you use the `typeKey` option, it changes the name of the property that defines a type, in this key you are changing it from `type` to `$type`. If you look at owner, you are using `type` here to define it as being another schema. Change that to `$type` and it should work. [Relevant documentation.](https://mongoosejs.com/docs/guide.html#typeKey)

**Comment by christian-the-brewer** [comment]
wow it looks like that worked! thanks matt! 
```
movie: {
  contentId: 766507,
  title: 'Prey',
  poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
  release_date: '2022-08-02',
  vote_average: 8.052,
  overview: 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
  tagline: 'They hunt to live. It lives to hunt.',
  genres: [
    { id: 28, name: 'Action' },
    { id: 878, name: 'Science Fiction' },
    { id: 27, name: 'Horror' }
  ],
  runtime: 100,
  type: 'movie'
}
create new favorites list : {
  _id: new ObjectId("63092928e66da25d7b2cd2f2"),
  content: [
    {
      contentId: 766507,
      title: 'Prey',
      poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
      release_date: '2022-08-02',
      vote_average: 8.052,
      overview: 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
      tagline: 'They hunt to live. It lives to hunt.',
      genre: [],
      runtime: 100,
      type: 'movie',
      _id: new ObjectId("63092928e66da25d7b2cd2f3")
    }
  ],
  owner: new ObjectId("63092906e66da25d7b2cd2ec"),
  createdAt: 2022-08-26T20:12:24.228Z,
  updatedAt: 2022-08-26T20:12:24.228Z,
  __v: 0
}
newfavorites.content: [
  {
    contentId: 766507,
    title: 'Prey',
    poster_path: '/ujr5pztc1oitbe7ViMUOilFaJ7s.jpg',
    release_date: '2022-08-02',
    vote_average: 8.052,
    overview: 'When danger threatens her camp, the fierce and highly skilled Comanche warrior Naru sets out to protect her people. But the prey she stalks turns out to be a highly evolved alien predator with a technically advanced arsenal.',
    tagline: 'They hunt to live. It lives to hunt.',
    genre: [],
    runtime: 100,
    type: 'movie',
    _id: new ObjectId("63092928e66da25d7b2cd2f3")
  }
]


``` 
I am going to check to see if I can send over the data now

**Comment by christian-the-brewer** [comment]
It works! thank you so much matt! my favorites components is populated with the favorites data. closing!
