### ISSUE TITLE
Schema error

### ISSUE THREAD

**Issue by erisha** [sei-ec-remote/project-4-issues#153]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN
### What's the problem you're trying to solve?
error message about schema. Idk why I'm getting this error now it was fine when I wrote it 

### Post any code you think might be relevant (one fenced block per file)
```
const mongoose = require('mongoose')

const Schema = mongoose.Schema

const ZodiacSign = new Schema (
	{
		zodiacSign: {
			name: String,
			required: true,
		}
	}
)




const ZodiacTeaSchema = new Schema(
	{
        zodiacSign: {
            name: String,
            required: true,
        },
        imagelink: String,
		name: {
			type: String,
			required: true,
		},
		description: {
			type: String,
			required: true,
		},
		price: {
			type: Number,
			required: true,
		}
		
	}
	
)

module.exports = mongoose.model('ZodiacTea', ZodiacTeaSchema)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:1066
    throw new TypeError(`Invalid schema configuration: \`${name}\` is not ` +
    ^

TypeError: Invalid schema configuration: `True` is not a valid type at path `zodiacSign.required`. See http://bit.ly/mongoose-schematypes for a list of valid schema types.
    at Schema.interpretAsType (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:1066:11)
    at Schema.path (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:710:27)
    at Schema.add (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:527:12)
    at Schema.add (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:539:12)
    at new Schema (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/node_modules/mongoose/lib/schema.js:128:10)
    at Object.<anonymous> (/Users/erisha/sei_icepops/projects/project4/Astrology_App-Backend/whats_tea/app/models/zodiacTea.js:5:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

### What is your best guess as to the source of the problem?
not sure.

### What things have you already tried to solve the problem?

tried changing the name property. That didn't work

**Paste a link to your repository here**
https://github.com/erisha/Astrology_App-Backend.git

not updated to current

**Comment by erisha** [comment]
fixed it
