### ISSUE TITLE
error running server djano

### ISSUE THREAD

**Issue by Salam3377** [sei-ec-remote/project-4-issues#162]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
I am trying to runserver on django and im getting some error
plus i am not sure if django and react are connected 

### Post any code you think might be relevant (one fenced block per file)
```
$ python manage.py runserver
Traceback (most recent call last):
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\commands\runserver.py", line 81, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 92, in __getattr__
    self._setup(name)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\salam\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_auth_template'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\salam\sei_monster_mash\projects\capestone_project\django\lux-house\manage.py", line 21, in <module>
    main()
  File "C:\Users\salam\sei_monster_mash\projects\capestone_project\django\lux-house\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\core\management\base.py", line 415, in run_from_argv
    connections.close_all()
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\connection.py", line 76, in all
    return [
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\connection.py", line 73, in __iter__
    return iter(self.settings)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\db\utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\utils\connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 92, in __getattr__
    self._setup(name)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\salam\.virtualenvs\django-0IsvbXhq\lib\site-packages\django\conf\__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\salam\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_auth_template'

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
ModuleNotFoundError: No module named 'django_auth_template'
```

### What is your best guess as to the source of the problem?
i am not so sure now,  there are for sure some more things i need to rename in boilerplate and set it up properly

### What things have you already tried to solve the problem?
i tried some options but its the same
**Paste a link to your repository here**
https://github.com/Salam3377/Django-lux-house

**Comment by Salam3377** [comment]
fixed it
