### ISSUE TITLE
Migrate issue

### ISSUE THREAD

**Issue by katherine-kania** [sei-ec-remote/project-4-issues#19]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR

### What's the problem you're trying to solve?
When I run migrate for order, I get an error and it won't allow the migration.
I want to make sure I am setting up my model and foreign keys correctly.

### Post any code you think might be relevant (one fenced block per file)
```
from django.db import models
from django.contrib.auth import get_user_model
from .flower import Flower

# Create your models here.
class Order(models.Model):
  # define fields
  # https://docs.djangoproject.com/en/3.0/ref/models/fields/

  name= models.CharField(max_length=100)
  size= models.CharField(max_length=100)
  price_range = models.CharField(max_length=100)
  color = models.CharField(max_length=100)
  flower = models.ForeignKey(
      Flower,
      on_delete=models.CASCADE
  )
  vase = models.CharField(max_length=100)
  owner = models.ForeignKey(
      get_user_model(),
      on_delete=models.CASCADE
  )

  def __str__(self):
    # This must return a string
    return f"The order named '{self.name}' is {self.color} in color."

  def as_dict(self):
    """Returns dictionary version of Order models"""
    return {
        'id': self.id,
        'name': self.name,
        'size': self.size,
        'price_range': self.price_range,
        'color': self.color,
        'vase': self.vase_mat
    }

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
Operations to perform:
  Apply all migrations: admin, api, auth, authtoken, contenttypes, sessions
Running migrations:
  Applying api.0003_auto_20220425_1906...Traceback (most recent call last):
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "api_order" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kasiakania/sei/django-env/project-4-api/manage.py", line 21, in <module>
    main()
  File "/Users/kasiakania/sei/django-env/project-4-api/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 231, in handle
    post_migrate_state = executor.migrate(
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 324, in create_model
    self.execute(sql, params or None)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/kasiakania/.local/share/virtualenvs/django-env-uJC-_q8V/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "api_order" already exists
```

### What is your best guess as to the source of the problem?
The flower foriegn key.

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/katherine-kania/project-4-api

**Comment by katherine-kania** [comment]
When I run the server, I get this notification:
![image](https://user-images.githubusercontent.com/98362705/165160495-d16addca-1f29-40cc-8d3c-824a0534b93b.png)

**Comment by cory-yonomi** [comment]
Can you post the error you get when you run the migrations as well?

**Comment by katherine-kania** [comment]
I don't get an error with makemigrations. I do get one when I run migrate.
![image](https://user-images.githubusercontent.com/98362705/165161758-a12d15c4-0751-4ea8-8aec-3889ee3fa6e4.png)
![image](https://user-images.githubusercontent.com/98362705/165161820-8262688f-3356-49ab-8d66-b5e150902894.png)

**Comment by cory-yonomi** [comment]
Do you have anywhere in the code that might be trying to create the table twice? Or is there another Order table somewhere in your Postgres? Referencing this question:

https://stackoverflow.com/questions/8792912/postgresql-error-relation-already-exists

**Comment by DoireannJane** [comment]
Solution: Drop db, recreate db, delete migrations and remigrate 🌟
