### ISSUE TITLE
Can't post a Santa's Secret in SantasSecretsForm

### ISSUE THREAD

**Issue by emilybernard1** [sei-ec-remote/project-4-issues#204]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I get an error when trying to hit the "submit" button in my SantasSecretsForm.

### Post any code you think might be relevant (one fenced block per file)
```
import React from 'react'
import { Form, Container, Button } from 'react-bootstrap'
import santasSecrets from './ShowSantasSecrets'

const SantasSecretForm = (props) => {
    const { santasSecret, wishList, handleChange, handleSubmit, heading } = props

    console.log('this is santasSecret in the form\n', santasSecret)

    return (
        <Container className="justify-content-center" style={{ fontFamily: "Oswald" }}>
            <h3>{heading}</h3>
            <Form onSubmit={handleSubmit}>
                <Form.Label>Name:</Form.Label>
                <Form.Control
                    placeholder="what's your recipient's name?"
                    name="name"
                    id="name"
                    value={santasSecret.name}
                    onChange={handleChange}
                />
                <Form.Label>Wish List for Santa:</Form.Label>
                <Form.Control
                    placeholder="what would you like Santa to bring this person..."
                    name="secret"
                    id="secret"
                    value={santasSecret.secret}
                    onChange={handleChange}
                />
                <Button id="button" className="m-3 justify-content-end" type="submit"> Submit </Button>
            </Form>
        </Container>
    )
}

export default SantasSecretForm
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
"Oh no! Something went wrong!"
```
:8000/santasSecrets/638800516fab2c051c755ef9:1          Failed to load resource: the server responded with a status of 404 (Not Found)
```
```
Uncaught (in promise) 
AxiosError
code
: 
"ERR_BAD_REQUEST"
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message
: 
"Request failed with status code 404"
name
: 
"AxiosError"
request
: 
XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response
: 
{data: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta char…s/638800516fab2c051c755ef9</pre>\n</body>\n</html>\n', status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, …}
stack
: 
"AxiosError: Request failed with status code 404\n    at settle (http://localhost:3001/static/js/bundle.js:61606:12)\n    at XMLHttpRequest.onloadend (http://localhost:3001/static/js/bundle.js:60320:66)"
[[Prototype]]
: 
Error
```

### What is your best guess as to the source of the problem?
Well, the 404 error not found means the browser has connected and sent the request to the web server. But I'm not sure why. The console log shows that it got the info I put in, but it just won't post it. 

### What things have you already tried to solve the problem?
I've combed through the error messages and my and searched on google, but I'm afraid of breaking my app if I proceed alone at this point because I don't yet understand what's going wrong and exactly how to fix it.

**Paste a link to your repository here**
https://github.com/emilybernard1/santas-helper
https://github.com/emilybernard1/SantasHelperBackEnd

**Comment by emilybernard1** [comment]
Andrew helped me squash the bug!
