### ISSUE TITLE
Postman not populating my tags?

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-4-issues#21]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

MERN(mongoose + react)

### What's the problem you're trying to solve?

I am currently try to test if I can get tags to populate in my main model on Postman. 

### Post any code you think might be relevant (one fenced block per file)
what I have in Postman

```
{
    "setup": {
        "title": "station1edited",
        "img": "https://imgur.com/r/battlestations/nsFcTI6",
        "description": "BLAHBLAHBLAH Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse a purus ornare est eleifend mollis at sit amet diam. Sed nec vulputate sapien. Nulla dolor lacus, posuere molestie eleifend sit amet, viverra nec nulla. Integer tempor porttitor ante et consectetur. Phasellus a tempor ex. In sed ultrices velit, eu fringilla arcu. Duis elit sem, blandit vitae leo non, sodales blandit libero. Aliquam mi nulla, condimentum nec sollicitudin a, feugiat vel nulla. Vivamus luctus ornare risus eget pulvinar. Vivamus dolor dui, varius vitae velit ultrices, vulputate ultrices ligula.",
        "tags":[
            {
                "text": "modern"
            }
        ],
        "comments": [
            {
                "note": "HELLLO"
            }
        ]
    }
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
 15:04:33 GMT-0500 (Central Daylight Time):
CastError: Cast to [ObjectId] failed for value "[ { text: 'modern' } ]" (type string) at path "tags.0"
    at model.Query.exec (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/query.js:4584:21)
    at model.Query.Query.then (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/query.js:4683:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: `"[ { text: 'modern' } ]"`,
  kind: '[ObjectId]',
  value: "[ { text: 'modern' } ]",
  path: 'tags.0',
  reason: CastError: Cast to ObjectId failed for value "{ text: 'modern' }" (type Object) at path "tags"
      at ObjectId.cast (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schema/objectid.js:247:11)
      at ObjectId.SchemaType.applySetters (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1135:12)
      at SchemaArray.cast (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schema/array.js:385:32)
      at SchemaArray.SchemaType.applySetters (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1135:12)
      at SchemaArray.SchemaType._castForQuery (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1567:15)
      at SchemaArray.SchemaType.castForQueryWrapper (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1529:22)
      at castUpdateVal (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/helpers/query/castUpdate.js:523:19)
      at walkUpdatePath (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/helpers/query/castUpdate.js:343:24)
      at castUpdate (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/helpers/query/castUpdate.js:95:7)
      at model.Query._castUpdate (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/query.js:4793:10) {
    stringValue: `"{ text: 'modern' }"`,
    messageFormat: undefined,
    kind: 'ObjectId',
    value: { text: 'modern' },
    path: 'tags',
    reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
        at new BSONTypeError (/Users/ivyle/sei/projects/project4/node_modules/bson/lib/error.js:41:28)
        at new ObjectId (/Users/ivyle/sei/projects/project4/node_modules/bson/lib/objectid.js:65:23)
        at castObjectId (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/cast/objectid.js:25:12)
        at ObjectId.cast (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schema/objectid.js:245:12)
        at ObjectId.SchemaType.applySetters (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1135:12)
        at SchemaArray.cast (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schema/array.js:385:32)
        at SchemaArray.SchemaType.applySetters (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1135:12)
        at SchemaArray.SchemaType._castForQuery (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1567:15)
        at SchemaArray.SchemaType.castForQueryWrapper (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/schematype.js:1529:22)
        at castUpdateVal (/Users/ivyle/sei/projects/project4/node_modules/mongoose/lib/helpers/query/castUpdate.js:523:19),
    valueType: 'Object'
  },
  valueType: 'string'
}

```

### What is your best guess as to the source of the problem?

Syntax?

### What things have you already tried to solve the problem?

I tried changing up my syntax and also checking the model files.

**Paste a link to your repository here**

https://github.com/ivycle94/Project-4-api

**Comment by timmshinbone** [comment]
share your model files in separate code blocks

**Comment by ivycle94** [comment]
setup.js (the battlestation)
``` const mongoose = require('mongoose')
const User = require('./user')
const Tag = require('./tag')
const commentSchema = require('./comment')
const { Schema, model } = mongoose

const setupSchema = new mongoose.Schema(
    {
        title: {
            type: String,
            required: true,
        },
        img: {
            type: String,
            required: true,
        },
        description: {
            type: String,
            required: true,
        },
        tags: [{
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Tag'
        }],
        owner: {
            type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
        },
        comments: [commentSchema]
    },
    {timestamps: true,}
)



module.exports = mongoose.model('Setup', setupSchema)
```
tag.js
```const mongoose = require('mongoose')

const tagSchema = new mongoose.Schema(
	{
		text: {
			type: String,
			required: true,
		},
		setup: [{
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Setup'
		}],
	},
	{timestamps: true,}
)

module.exports = mongoose.model('Tag', tagSchema)
```

**Comment by cory-yonomi** [comment]
You have your SetUp model using an array of references for tags, versus an array of subdocuments. Your tag in your Postman object would need to be an ID or array of IDs the way you're currently set up.

**Comment by ivycle94** [comment]
That make sense, but the part that I am confused about is if I don't currently have an ID for the tag then how would I get one to test on postman? Would I need to do another set of routes for a tag creation to get the ID first before?

**Comment by ivycle94** [comment]
Like this:

![Screen Shot 2022-04-25 at 3 40 11 PM](https://user-images.githubusercontent.com/20195643/165171187-fe65335f-18f1-4c20-b545-7c6dd5c4d439.png)

**Comment by cory-yonomi** [comment]
Correct! You'd have to create them to get the IDs to include in the array

**Comment by ivycle94** [comment]
okie dokie thanks cory!
