### ISSUE TITLE
IDs render on page but wont generate in URL

### ISSUE THREAD

**Issue by joshuaharris1103** [sei-ec-remote/project-4-issues#241]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Why my IDs wont show up in URL causing issues with my crud

### Post any code you think might be relevant (one fenced block per file)
```
import apiUrl from '../apiConfig'
import axios from 'axios'

// READ -> Index
export const getAllRecipes = (user) => {
    console.log('GET ALL RECIPES')
    return axios({
        url: `${apiUrl}/recipes`,
        method: 'GET',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}

// READ -> Show
export const getOneRecipe = (_id) => {
    return axios(`${apiUrl}/recipes/${_id}`)
}

// Create (create a Recipe)
export const createRecipe = (user, newRecipe) => {
    console.log('this is the user', user)
    console.log('this is the new recipe', newRecipe)
    return axios({
        url: `${apiUrl}/recipes`,
        method: 'POST',
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { recipe: newRecipe }
    })
}

// Update (update a Recipe)
export const updateRecipe = (user, updatedRecipe) => {
    return axios({
        url: `${apiUrl}/recipes/${updatedRecipe.id}`,
        method: 'PATCH',
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { Recipe: updatedRecipe }
    })
}

// Delete (delete a Recipe)
export const removeRecipe = (user, recipeId) => {
    return axios({
        url: `${apiUrl}/recipes/${recipeId}`,
        method: 'DELETE',
        headers: {
            Authorization: `Token token=${user.token}`
        }
    })
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Console:
GET http://localhost:8000/recipes/undefined 401 (Unauthorized)
when I try to go to show page

GET http://localhost:8000/recipes/640fcb6ea2338847fe50e92b 401 (Unauthorized)
When I manually punch the ID in I'm still unauthorized

### What is your best guess as to the source of the problem?
I would assume it has to do with my authorization but these routes are working just fine in postman

### What things have you already tried to solve the problem?
Postman testing, starting from scratch with the code

**Paste a link to your repository here**
https://github.com/joshuaharris1103/FoodFactor/tree/v2

**Comment by asands94** [comment]
Is your frontend using port 8000? When you click on an item in your frontend do you get any error messages in terminal?

**Comment by joshuaharris1103** [comment]
Yes my ports are doing fine its just when I try to get to my show page i have issues. I see an error in the console  : 
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `RecipeIndex`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at RecipeIndex (http://localhost:3000/static/js/main.chunk.js:2728:87)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:62675:5
    at Home (http://localhost:3000/static/js/main.chunk.js:863:23)
    at RequireAuth (http://localhost:3000/static/js/main.chunk.js:4162:5)
    at RenderedRoute (http://localhost:3000/static/js/vendors~main.chunk.js:103047:5)
    at Routes (http://localhost:3000/static/js/vendors~main.chunk.js:103512:5)
    at App (http://localhost:3000/static/js/main.chunk.js:120:81)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:103450:15)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:101644:5)
```

**Comment by joshuaharris1103** [comment]
The terminal gives me nothing

**Comment by asands94** [comment]
Can you show your RecipeIndex component

**Comment by joshuaharris1103** [comment]
```
import { useState, useEffect } from 'react'
import Card from 'react-bootstrap/Card'
import { Link } from 'react-router-dom'
import { Avatar } from '@material-ui/core'

// api function from our api file
import { getAllRecipes } from '../../api/recipe'

// need our messages from our autodismissalert directory
import messages from '../shared/AutoDismissAlert/messages'

// this is a styling object. they're a quick easy way add focused css properties to our react components
const cardContainerStyle = {
    margin: '10px',
    border: '10px',
    width: '80%',
    maxWidth: '100%',
    padding: '20px',
    display: 'flex',
    flexFlow: 'row wrap',
    justifyContent: 'center'
}
{/* <div className='card' 
            style= {{margin: '10px auto', 
            maxWidth: '75%', 
            padding: '20px', 
            textAlign:'center'}}> */}

// RecipeIndex will make a request to the API for all Recipe
// once it receives a response, display a card for each recipes
const RecipeIndex = (props) => {
    const [recipes, setRecipes] = useState(null)
    const [error, setError] = useState(false)
    console.log('these are the recipes in index', recipes)

    // pull the message alert (msgAlert) from props
    const { user, msgAlert, caption, image, recipeName } = props

    // get our Recipe from the api when the component mounts
    useEffect(() => {
        getAllRecipes(user)
            .then(res => setRecipes(res.data.recipes))
            .catch(err => {
                msgAlert({
                    heading: 'Error getting recipes',
                    message: messages.getRecipeFailure,
                    variant: 'danger'
                })
                setError(true)
            })
    }, [])

    console.log("here are your recipes", recipes)
    
    // if error, display an error
    if (error) {
        return <p>Error!</p>
    }

    // console.log('this is owner', recipes._id)

    if (!recipes) {
        // if no Recipe loaded yet, display 'loading'
        return <p>...loading ...please wait</p>
    } else if (recipes.length === 0) {
        // otherwise if there ARE no Recipe, display that message
        return <p>No recipes yet, go add some!</p>
    }

    // once we have an array of Recipe, loop over them
    // produce one card for every recipes
    
    console.log('owner is',recipes.owner)
    console.log('caption is',recipes.caption)
    console.log('name is',recipes.name)
    console.log('id is',recipes.id)
    console.log('_id is',recipes._id)
    const recipeCards = recipes.map(recipes => (
        // <Card key={ recipes.id } style={{ width: '30%', margin: 5 }}>
        //     <Card.Header>{ recipes.fullTitle }</Card.Header>
        //     <Card.Body>
        //         <Card.Text>
        //             <Link to={`/recipes/${recipes.id}`} className="btn btn-info">View { recipes.owner }</Link>
        //         </Card.Text>
        //     </Card.Body>
        // </Card>
        
        <div className='post'>
        {/* header -> profile pic & username */}
        <div className="post_header">
            <Avatar
                className='post_avatar'
                alt='UserPhoto'
                // this is where users will have uploaded profile pictures
                src=''
                />
            <h3>{ recipes.username }</h3>
            {/* <h3>{ user.username }</h3> this display's logged in user's @ */}
            {/* this should be the user's @ */}
        </div>
        
        {/* image */}
        <img className='post_image' src={ recipes.image }/>
        <Link to={`/recipes/${recipes.id}`} className="btn btn-info">View Recipe { recipes.recipeName }</Link>
        {/* username & caption */}
        <h4 className='post_text'><strong><a href='/recipes/${recipes.id}' style={{textDecoration:"none", color: 'grey'}}> { recipes._id }:</a>{/*username*/}</strong> { recipes.caption }</h4>

        {/* Like Post */}
        {/* <h6>{recipes.likes.length}</h6> */}
        <h6>{recipes.recipeName}</h6>
        <i className="material-icons" style={{color: 'grey'}}>thumb_up</i>
        <i className="material-icons" style={{color: 'grey'}}>thumb_down</i>
        <br/>
        <br/>
        <h6>Add to Meal Plan<i className="material-icons" style={{color: 'red'}}>favorite</i></h6>
        

        {/* Comments */}
        <input type='text' placeholder='add a comment'/>



    </div>
    ))
    console.log('this is usernameID', recipes._id) 
    // the id shows in line 102 but not 121?////////////////////////////
    // return some jsx, a container with all the recipecards
    return (
        <div className="container-md" style={ cardContainerStyle }>
            { recipeCards }
        </div>
    )
}

// export our component
export default RecipeIndex
```

**Comment by asands94** [comment]
Not sure why that page was throwing an error. Are you able to login and return user information? Check for that to make sure you are actually getting a token

**Comment by joshuaharris1103** [comment]
Yes I am. I console-logged the user.token and it shows

**Comment by asands94** [comment]
After lunch we can head into a breakout room to get you sorted before outcomes
