### ISSUE TITLE
Unable to start React app

### ISSUE THREAD

**Issue by NoahCSmith93** [sei-ec-remote/project-4-issues#259]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
React app encounters an error when trying to start

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/noahsmith/sei/projects/XIV-BiStro/XIV-BiStro-Client/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}```

### What is your best guess as to the source of the problem?
No idea

### What things have you already tried to solve the problem?
I made sure to run `npm install` before attempting to start it

**Paste a link to your repository here**
https://github.com/NoahCSmith93/XIV-BiStro-Client

**Comment by asands94** [comment]
Hey Noah, it looks like you need to update your Package.json file. Here are the commands to run in terminal after you cd into your React app. Just make sure when you do an` ls `in your terminal you can see your package.json before running these commands.

Run one at a time.

`npm i -g npm-check-updates`
`ncu -u`
`npm install`

**Comment by asands94** [comment]
If `ncu -u` doesn't work, you can do this instead `npx npm-check-updates -u`

**Comment by NoahCSmith93** [comment]
Thanks, that solved it
