### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by RyanCLuis** [sei-ec-remote/project-4-issues#283]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
im testing my backend with Postman and the params have failed a Mongoose validation

### Post any code you think might be relevant (one fenced block per file)
```
const userSchema = new mongoose.Schema(
	{
		username: {
			type: String,
			required: true,
			unique: true,
		},
		email: {
			type: String,
			required: true,
			unique: true,
		},
		hashedPassword: {
			type: String,
			required: true,
		},
		image: {
			type: String,
			default: "",
		},
		token: String,
	},
	{
		timestamps: true,
		toObject: {
			// remove `hashedPassword` field when we call `.toObject`
			transform: (_doc, user) => {
				delete user.hashedPassword
				return user
			},
		},
	}
)

module.exports = mongoose.model('User', userSchema)
```
this is my user model

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
im Postman i see 
```
{
    "status": 422,
    "message": "The receieved params failed a Mongoose validation"
}
```
and in my terminal i see 
```
===== Incoming Request =====

Fri Feb 09 2024 07:23:01 GMT-0800 (Pacific Standard Time)
POST /sign-up
body {"credentials":{"username":"ryan","email":"r@r.com","password":"r","password_confirmation":"r","image":""}}

============================


 07:23:01 GMT-0800 (Pacific Standard Time):
Error: User validation failed: username: Path `username` is required.
    at ValidationError.inspect (/root/sei/projects/ListenApi/listenApi/node_modules/mongoose/lib/error/validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2279:40)
    at formatWithOptions (node:internal/util/inspect:2141:10)
    at console.value (node:internal/console/constructor:352:14)
    at console.warn (node:internal/console/constructor:385:61)
    at module.exports (/root/sei/projects/ListenApi/listenApi/lib/error_handler.js:12:11)
    at Layer.handle_error (/root/sei/projects/ListenApi/listenApi/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/root/sei/projects/ListenApi/listenApi/node_modules/express/lib/router/index.js:326:13) {
  errors: {
    username: ValidatorError: Path `username` is required.
        at validate (/root/sei/projects/ListenApi/listenApi/node_modules/mongoose/lib/schematype.js:1365:13)
        at SchemaType.doValidate (/root/sei/projects/ListenApi/listenApi/node_modules/mongoose/lib/schematype.js:1349:7)
        at /root/sei/projects/ListenApi/listenApi/node_modules/mongoose/lib/document.js:2985:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'username',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
```

### What is your best guess as to the source of the problem?
something about Mongoose not accepting my username?

### What things have you already tried to solve the problem?
ive done r for username and it failed, tried changing it to more unique and it failed

**Paste a link to your repository here**
https://github.com/RyanCLuis/ListenAPI

**Comment by nayaba** [comment]
What's the URL you're using in postman?

**Comment by RyanCLuis** [comment]
http://localhost:8000/sign-up

**Comment by nayaba** [comment]
And can you share your sign up controller?

**Comment by RyanCLuis** [comment]
```
router.post('/sign-up', (req, res, next) => {
	// start a promise chain, so that any errors will pass to `handle`
	Promise.resolve(req.body.credentials)
		// reject any requests where `credentials.password` is not present, or where
		// the password is an empty string
		.then((credentials) => {
			if (
				!credentials ||
				!credentials.password ||
				credentials.password !== credentials.password_confirmation
			) {
				throw new BadParamsError()
			}
		})
		// generate a hash from the provided password, returning a promise
		.then(() => bcrypt.hash(req.body.credentials.password, bcryptSaltRounds))
		.then((hash) => {
			// return necessary params to create a user
			return {
				email: req.body.credentials.email,
				hashedPassword: hash,
			}
		})
		// create user with provided email and hashed password
		.then((user) => User.create(user))
		// send the new user object back with status 201, but `hashedPassword`
		// won't be send because of the `transform` in the User model
		.then((user) => res.status(201).json({ user: user.toObject() }))
		// pass any errors along to the error handler
		.catch(next)
})
```

**Comment by nayaba** [comment]
So in your controller you're returning email and hashedPassword here:

```js
		.then((hash) => {
			// return necessary params to create a user
			return {
				email: req.body.credentials.email,
				hashedPassword: hash,
			}
		})
```

But your user model also requires a username, which is why you're getting this error:
```
Error: User validation failed: username: Path `username` is required.
```

The username is required at creation.  But since you also have an image field, you might consider adding that at creation as well.

**Comment by RyanCLuis** [comment]
the image field is not required in sign-up, but ill add the username in the return

**Comment by RyanCLuis** [comment]
returning username: req.body.credentials.username worked, thankyou!
