### ISSUE TITLE
Attempting to add username to signup form

### ISSUE THREAD

**Issue by da1dude** [sei-ec-remote/project-4-issues#287]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
userName is not being passed in the credentials variable to the back end to sign up a new user.

### Post any code you think might be relevant (one fenced block per file)

SIGNUP.JS
```js
// import React, { Component } from 'react'
import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { signUp, signIn } from '../../api/auth'
import messages from '../shared/AutoDismissAlert/messages'

import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'

const SignUp = (props) => {
	// constructor(props) {
	// 	super(props)

	// 	this.state = {
	// 		email: '',
	// 		password: '',
	// 		passwordConfirmation: '',
	// 	}
	// }    
    const [email, setEmail] = useState('')
    const [userName, setUserName] = useState('')
    const [password, setPassword] = useState('')
    const [passwordConfirmation, setPasswordConfirmation] = useState('')

    const navigate = useNavigate()

	const onSignUp = (event) => {
		event.preventDefault()

		const { msgAlert, setUser } = props

        const credentials = {email, userName, password, passwordConfirmation}

		signUp(credentials)
			.then(() => signIn(credentials))
			.then((res) => setUser(res.data.user))
			.then(() =>
				msgAlert({
					heading: 'Sign Up Success',
					message: messages.signUpSuccess,
					variant: 'success',
				})
			)
			.then(() => navigate('/'))
			.catch((error) => {
                setEmail('')
                setUserName('')
                setPassword('')
                setPasswordConfirmation('')
				msgAlert({
					heading: 'Sign Up Failed with error: ' + error.message,
					message: messages.signUpFailure,
					variant: 'danger',
				})
			})
	}


    return (
        <div className='row'>
            <div className='col-sm-10 col-md-8 mx-auto mt-5'>
                <h3>Sign Up</h3>
                <Form onSubmit={onSignUp}>
                    <Form.Group controlId='email'>
                        <Form.Label>Email address</Form.Label>
                        <Form.Control
                            required
                            type='email'
                            name='email'
                            value={email}
                            placeholder='Enter email'
                            onChange={e => setEmail(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId='userName'>
                        <Form.Label>User Name</Form.Label>
                        <Form.Control
                            required
                            type='userName'
                            name='userName'
                            value={userName}
                            placeholder='Enter a user name'
                            onChange={e => setUserName(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId='password'>
                        <Form.Label>Password</Form.Label>
                        <Form.Control
                            required
                            name='password'
                            value={password}
                            type='password'
                            placeholder='Password'
                            onChange={e => setPassword(e.target.value)}
                        />
                    </Form.Group>
                    <Form.Group controlId='passwordConfirmation'>
                        <Form.Label>Password Confirmation</Form.Label>
                        <Form.Control
                            required
                            name='passwordConfirmation'
                            value={passwordConfirmation}
                            type='password'
                            placeholder='Confirm Password'
                            onChange={e => setPasswordConfirmation(e.target.value)}
                        />
                    </Form.Group>
                    <Button variant='primary' type='submit'>
                        Submit
                    </Button>
                </Form>
            </div>
        </div>
    )

}

export default SignUp
```

SIGNUP route
```js
// SIGN UP
// POST /sign-up
router.post('/sign-up', (req, res, next) => {
	// start a promise chain, so that any errors will pass to `handle`
	Promise.resolve(req.body.credentials)
		// reject any requests where `credentials.password` is not present, or where
		// the password is an empty string
		.then((credentials) => {
			if (
				!credentials ||
				!credentials.password ||
				credentials.password !== credentials.password_confirmation
			) {
				throw new BadParamsError()
			}
		})
		// generate a hash from the provided password, returning a promise
		.then(() => bcrypt.hash(req.body.credentials.password, bcryptSaltRounds))
		.then((hash) => {
			// return necessary params to create a user
			return {
				userName: req.body.credentials.userName,
				email: req.body.credentials.email,
				hashedPassword: hash,
			}
		})
		// create user with provided email and hashed password
		.then((user) => User.create(user))
		// send the new user object back with status 201, but `hashedPassword`
		// won't be send because of the `transform` in the User model
		.then((user) => res.status(201).json({ user: user.toObject() }))
		// pass any errors along to the error handler
		.catch(next)
})
```

SCHEMA

```js
const userSchema = new mongoose.Schema(
	{
		email: {
			type: String,
			required: true,
			unique: true,
		},
		userName: {
			type: String,
			required: true,
			unique: true,
		},
		hashedPassword: {
			type: String,
			required: true,
		},
		profile: [profileSchema],
		token: String,
	},
	{
		timestamps: true,
		toObject: {
			// remove `hashedPassword` field when we call `.toObject`
			transform: (_doc, user) => {
				delete user.hashedPassword
				return user
			},
		},
	}
)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```text
 15:31:22 GMT-0600 (Central Standard Time):
Error: User validation failed: userName: Path `userName` is required.
    at ValidationError.inspect (/Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/lib/error/validation.js:50:26)
    at formatValue (node:internal/util/inspect:805:19)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2279:40)
    at formatWithOptions (node:internal/util/inspect:2141:10)
    at console.value (node:internal/console/constructor:352:14)
    at console.warn (node:internal/console/constructor:385:61)
    at module.exports (/Users/pk23939/code/sei/projects/gameHubApi/lib/error_handler.js:12:11)
    at Layer.handle_error (/Users/pk23939/code/sei/projects/gameHubApi/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/pk23939/code/sei/projects/gameHubApi/node_modules/express/lib/router/index.js:326:13) {
  errors: {
    userName: ValidatorError: Path `userName` is required.
        at validate (/Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/lib/schematype.js:1365:13)
        at SchemaType.doValidate (/Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/lib/schematype.js:1349:7)
        at /Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/lib/document.js:2985:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'userName',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
```

### What is your best guess as to the source of the problem?
Im unsure. I believe I have copied everything that was required using email as a reference.

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/da1dude/clientGameHub

**Comment by timmshinbone** [comment]
try changing type to 'text' in the form, also add a console log to the sign up function that will print the request body you're trying to send, that way we can make sure it looks right

**Comment by timmshinbone** [comment]
I meant change the type to be text in the form field for userName

**Comment by da1dude** [comment]
I didnt have the userName in the API call fixed that and now get this error. 

```text

 15:43:19 GMT-0600 (Central Standard Time):
MongoServerError: E11000 duplicate key error collection: gameHub.users index: user_1 dup key: { user: null }
    at /Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/node_modules/mongodb/lib/operations/insert.js:50:33
    at /Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/node_modules/mongodb/lib/operations/command.js:84:64
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  index: 0,
  code: 11000,
  keyPattern: { user: 1 },
  keyValue: { user: null },
  [Symbol(errorLabels)]: Set(0) {}
```

**Comment by timmshinbone** [comment]
Duplicate key error means you have `unique: true` and your trying to sign up someone or create something that already has that value in the database, which means some request worked at some point. Easiest way around this, either use another username, email or whatever it was, or drop your database on atlas

**Comment by da1dude** [comment]
The users im attempting to sign up with do not exist. I have verified in mongoDB

The functionality works in PostMan.

**Comment by da1dude** [comment]
Okay, I found the problem. I userName was called user prior and I changed it to userName because there was already a setUser state and it was conflicting. 

MongoDB didnt like that I guess. I dropped and recreated the database and everything worked.
