### ISSUE TITLE
Modal is throwing a Token error. 

### ISSUE THREAD

**Issue by da1dude** [sei-ec-remote/project-4-issues#290]
### What's the problem you're trying to solve?
Modal is throwing a token error, creates the object but wont PATCH to the backend. 

Been working on this for a while now. Ryan and John have no clue either.

### Post any code you think might be relevant (one fenced block per file)
```js
// UPDATE -> Adjust a game
export const updateGame = (user, updatedGame) => {
    return axios({
        url: `${apiUrl}/games/${updatedGame._id}`,
        method: 'PATCH',
        headers: {
            Authorization: `Token token=${user.token}`
        },
        data: { game: updatedGame }
    })
}

```

```js
edit game MODAL

import React, { useState } from 'react'
import { Modal } from 'react-bootstrap'
import WishForm from '../shared/WishForm'
import messages from '../shared/AutoDismissAlert/messages'

const EditGameModal = (props) => {

    const { user, show, handleClose, updateGame, msgAlert, triggerRefresh } = props

    const [game, setGame] = useState(props.game)

    const onChange = (e) => {
        e.persist()

        setGame(prevGame => {
            const updatedName = e.target.name
            let updatedValue = e.target.value

            const updatedGame = { [updatedName] : updatedValue }
            return {
                ...prevGame, ...updatedGame
            }
        })
    }
    console.log('this is user', user)
    const onSubmit = (e) => {
        e.preventDefault()
        // make the API call
        updateGame(user, game)
            // close the modal
            .then(() => handleClose())
            // message the user
            .then(() => {
                msgAlert({
                    heading: 'Oh Yeah!',
                    message: messages.updateGameSuccess,
                    variant: 'success'
                })
            })
            // trigger a refresh
            .then(() => triggerRefresh())
            // send error message if applicable
            .catch(() => {
                msgAlert({
                    heading: 'Oh no!',
                    message: messages.generalError,
                    variant: 'danger'
                })
            })
    }
    console.log('this is user after submit', user)
    return (
        <Modal show={show} onHide={handleClose}>
            <Modal.Header closeButton />
            <Modal.Body>
                <WishForm 
                    game={game}
                    handleChange={onChange}
                    handleSubmit={onSubmit}
                    heading="Update Game"
                />
            </Modal.Body>
        </Modal>
    )
}

export default EditGameModal
```
```js
WISH FORM
import { Form, Button, Container } from 'react-bootstrap'
import { createGame } from '../../api/game'
import { useNavigate } from 'react-router-dom'
import messages from '../shared/AutoDismissAlert/messages'





const WishForm = (props) => {
    const { user, wish, game, handleChange, msgAlert } = props
    const navigate = useNavigate()
    console.log('this is wishform line 9',wish || game)

    const onSubmit = (e) => {
        e.preventDefault()

        console.log('this is wish',wish || game)
        createGame(user, wish || game)
            .then(res => { navigate(`/games/`)})
            .then(() => {
                msgAlert({
                    heading: 'Oh Yeah!',
                    message: messages.createWishSuccess,
                    variant: 'success'
                })
            })
            .catch(err => {
                msgAlert({
                    heading: 'Oh no!',
                    message: messages.generalError,
                    variant: 'danger'
                })
            })
    }


return (
    <>
    <Container>
    <Form onSubmit={onSubmit}>
        <Form.Group hidden>
            <Form.Label>Id</Form.Label>
            <Form.Control
                name="rawgId"
                id='rawgId'
                value={game.id}
                onChange={handleChange}
            />
        </Form.Group>
        <Form.Group hidden>
            <Form.Label>Name</Form.Label>
            <Form.Control
                name="name"
                id='name'
                value={game.name}
                onChange={handleChange}
            />
        </Form.Group>
        <Form.Group hidden>
            <Form.Label>Description</Form.Label>
            <Form.Control
                name="description"
                id='description'
                value={game.description_raw}
                onChange={handleChange}
            />
        </Form.Group>
        <Form.Group hidden>
            <Form.Label>image</Form.Label>
            <Form.Control
                name="image"
                id='image'
                value={game.background_image}
                onChange={handleChange}
            />
        </Form.Group>
        <Form.Group hidden>
            <Form.Label>Score</Form.Label>
            <Form.Control
                name="rating"
                id='rating'
                value={game.rating}
                onChange={handleChange}
            />
        </Form.Group>
        <Button type="submit">Add to Wish List</Button>
        <Form.Group>
            <Form.Label>Add a comment for {game.name}</Form.Label>
            <Form.Control
                name="comment"
                id='comment'
                value={game.comment}
                onChange={handleChange}
            />
        </Form.Group>
        
    </Form>
    </Container>
    <br />
    <br />
    <br />
    </>
    )
}
export default WishForm

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```text
game.js:35 Uncaught TypeError: Cannot read properties of undefined (reading 'token')
    at createGame (game.js:35:1)
    at onSubmit (WishForm.jsx:19:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates$1 (react-dom.development.js:22396:1)
    at batchedEventUpdates (react-dom.development.js:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
```
### What is your best guess as to the source of the problem?

No clue. Tired of working on it. Dont want to wait till office hours to ask Tylus why im dumb. 

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/da1dude/clientGameHub

**Comment by timmshinbone** [comment]
You don't have a in that there token. Check to make sure your user's login is persisted, and that it's actually being inherited by that component. Looks like you aren't sending the user as a prop here:
![image](https://github.com/sei-ec-remote/project-4-issues/assets/55121526/856a7b26-cb03-4ed8-86de-09da5c542328)

**Comment by da1dude** [comment]
Okay that moved me along past that issue:

now im seeing
```text
===== Incoming Request =====

Tue Feb 13 2024 10:21:06 GMT-0600 (Central Standard Time)
POST /games
body {"game":{"_id":"65cb7bf1a89f841feb28b33d","rawgId":"3439","name":"Life is Strange","description":"Interactive storytelling and plot-heavy games gained popularity, and “Life is Strange” arrived as teen mystery adventure. The plot will go through the life of Maxine, a teenager in possession of curious power, allowing her to stop and rewind time, in order to manipulate her surroundings. Max, after the reunion with her friend Chloe, is on the path to uncovering the secrets of Arcadia Bay. Players will have to deal with puzzle solving through the fetch quests, in order to change the world around them. \nThe game puts players in situations, where they’re forced to make a moral choice, going through the decision which may have short-term or long-term consequences. Every choice made by the player will trigger the butterfly effect, surrounding the first playthrough of the game with a lot of emotional struggle, thoughtfully crafted by the developers at Dontnod Entertainment. Life is Strange is third person adventure game, where players might seem just as an observer of the stories, unfolding in front of them.","image":"https://media.rawg.io/media/games/562/562553814dd54e001a541e4ee83a591c.jpg","rating":"4.11","comment":"test","owner":"65cad8f11a48efea0156e027","createdAt":"2024-02-13T14:25:53.011Z","updatedAt":"2024-02-13T14:25:53.011Z","__v":0}}

============================


 10:21:06 GMT-0600 (Central Standard Time):
MongoServerError: E11000 duplicate key error collection: gameHub.games index: _id_ dup key: { _id: ObjectId('65cb7bf1a89f841feb28b33d') }
    at /Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/node_modules/mongodb/lib/operations/insert.js:50:33
    at /Users/pk23939/code/sei/projects/gameHubApi/node_modules/mongoose/node_modules/mongodb/lib/operations/command.js:84:64
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  index: 0,
  code: 11000,
  keyPattern: { _id: 1 },
  keyValue: { _id: new ObjectId("65cb7bf1a89f841feb28b33d") },
  [Symbol(errorLabels)]: Set(0) {}
}

```

**Comment by timmshinbone** [comment]
Duplicate key error means you have `unique: true` on one of your models, and you're trying to send the same data for a different instance of that resource

**Comment by da1dude** [comment]
No unique:true

```js

const gameSchema = new mongoose.Schema(
	{
		rawgId: {
			type: String,
			required: true,
		},
		name: {
			type: String,
			required: true,
		},
		description: {
			type: String,
			required: true,
		},
		image: {
			type: String,
			required: true,
		},
		rating: {
			type: String,
			required: true,
		},
		comment: {
			type: String,
		},
		owner: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
			required: true,
		},
	},
	{
		timestamps: true,
	},
	{
		timestamps: true,
		toObject: { virtuals: true},
		toJSON: { virtuals: true}
	}
)
```

**Comment by timmshinbone** [comment]
ok, share the controller you're hitting in the back end

**Comment by da1dude** [comment]
```js

// UPDATE
// PATCH /games/5a7db6c74d55bc51bdf39793
router.patch('/games/:id', requireToken, removeBlanks, (req, res, next) => {
	// if the client attempts to change the `owner` property by including a new
	// owner, prevent that by deleting that key/value pair
	delete req.body.game.owner

	Game.findById(req.params.id)
		.then(handle404)
		.then((game) => {
			// pass the `req` object and the Mongoose record to `requireOwnership`
			// it will throw an error if the current user isn't the owner
			requireOwnership(req, game)

			// pass the result of Mongoose's `.update` to the next `.then`
			return game.updateOne(req.body.game)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})

```

**Comment by da1dude** [comment]
If ya have a second. Id like to show ya what is happening.

**Comment by timmshinbone** [comment]
Yeah, jump on in to room 19
