### ISSUE TITLE
Delete order route giving me 500 error on Postman

### ISSUE THREAD

**Issue by irishjack490** [sei-ec-remote/project-4-issues#296]
### What stack are you using? 
MERN

### What's the problem you're trying to solve?
Testing the delete order route on postman, I am getting an error in the console indicating a TypeError: Cannot read properties of undefined (reading '_id')  at requireOwnership. The route does not delete orders :(

### Post any code you think might be relevant (one fenced block per file)
Here is the code for the route, I included a console.log to confirm if the order was found and it is displaying in the console
```
router.delete('/orders/delete-order/:orderId', requireToken, (req, res, next) => {
    const orderId = req.params.orderId;

    Order.findById(orderId)
        .then(handle404)
        .then((order) => {
            console.log('Found order:', order);
            
            requireOwnership(req, order);

            return order.deleteOne(); 
        })
        .then(() => {
            res.sendStatus(204);
        })
        .catch(next);
});

module.exports = router;
```
Just in case here is the model for the order
```
const orderSchema = new mongoose.Schema(
	{
		donut : {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Donut',
			required: true
		},

		donutQuantity: { 
			type: Number,
			default: 0
		},
	
		coffee: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Coffee',
			required: true
		},
		coffeeQuantity: {
			type: Number,
			default: 0
		},

		totalPrice: {
			type: Number,
			required: true,
		},
		owner: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
			
		},
        createdAt: {
            type: String,
            default: Date.now
        }
	}
	
)

```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
These are the errors coming up on the console

```
listening on port 8000

===== Incoming Request =====

Tue Feb 13 2024 14:24:10 GMT-0600 (Central Standard Time)
DELETE /orders/delete-order/65cb890e139aa545870053c8
body {"_id":"65cb890e139aa545870053c8","donuts":"65ca6d39931f775ef6a69741","donutQuantity":1,"coffee":"65ca7db77b22de6ae35a0a8a","coffeeQuantity":1,"totalPrice":3,"user":"65cb7fe3825b95a713192701"}

============================

Found order: {
  _id: new ObjectId("65cb890e139aa545870053c8"),
  donuts: new ObjectId("65ca6d39931f775ef6a69741"),
  donutQuantity: 1,
  coffee: new ObjectId("65ca7db77b22de6ae35a0a8a"),
  coffeeQuantity: 1,
  totalPrice: 3,
  user: new ObjectId("65cb7fe3825b95a713192701"),
  createdAt: '2024-02-13T15:21:49.293Z',
  __v: 0
}

 14:24:10 GMT-0600 (Central Standard Time):
TypeError: Cannot read properties of undefined (reading '_id')
    at requireOwnership (/home/irishjack/sei/projects/Project4/DonutShopApp/DonutsAPI/lib/custom_errors.js:46:31)
    at /home/irishjack/sei/projects/Project4/DonutShopApp/DonutsAPI/app/routes/order_routes.js:90:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


```

### What is your best guess as to the source of the problem?

requireOwnership not accepting what I am passing

### What things have you already tried to solve the problem?
I have tried to console.log the order, it displays.. I looked at the requireOwnership function, it looks correct..

Here is what I am using to delete the order in postman

```
{
            "_id": "65cb890e139aa545870053c8",
            "donuts": "65ca6d39931f775ef6a69741",
            "donutQuantity": 1,
            "coffee": "65ca7db77b22de6ae35a0a8a",
            "coffeeQuantity": 1,
            "totalPrice": 3,
            "user": "65cb7fe3825b95a713192701"            
        }
```

**Paste a link to your repository here**
https://github.com/irishjack490/Project4-DonutShop-MERN-Stack-App

Thank you!

**Comment by nayaba** [comment]
Your `requireOwnership` function is looking for an owner attribute on your req object:
```js
const requireOwnership = (requestObject, resource) => {
	// `requestObject.user` will be defined in any route that uses `requireToken`
	// `requireToken` MUST be passed to the route as a second argument
	const owner = resource.owner._id ? resource.owner._id : resource.owner
	//  check if the resource.owner is an object in case populate is being used
	//  if it is, use the `_id` property and if not, just use its value
	if (!requestObject.user._id.equals(owner)) {
		throw new OwnershipError()
	}
}
```
are you sending `requireOwnership` an owner with your req object?

**Comment by irishjack490** [comment]
I thought I was but I get that type error message saying cannot read the properties of (reading '_id')
Here is the code, how can I correct his?
```
router.delete('/orders/delete-order/:orderId', requireToken, (req, res, next) => {
    const orderId = req.params.orderId;
	

    Order.findById(orderId)
        .then(handle404)
        .then((order) => {
            console.log('Found order:', order);
            
            requireOwnership(req, req.user._id);

            return order.deleteOne(); 
        })
        .then(() => {
            res.sendStatus(204);
        })
        .catch(next);
});
```

**Comment by irishjack490** [comment]
I've also tried this :(

```
router.delete('/orders/delete-order/:orderId', requireToken, (req, res, next) => {
    const orderId = req.params.orderId;
	
    Order.findById(orderId)
        .then(handle404)
        .then((order) => {
            console.log('Found order:', order);
            
            requireOwnership(req, order);

            return order.deleteOne(); 
        })
        .then(() => {
            res.sendStatus(204);
        })
        .catch(next);
});


```

**Comment by nayaba** [comment]
If you console.log req just above where you're passing it to `requireOwnership(req, order);` does the output have a key of `owner` on it?

**Comment by irishjack490** [comment]
I get a huge array of objects but this is the only one referencing to an owner, I guess I got confused and thought the owner was  the id of the user, where can I go from here
```
[Symbol(async_id_symbol)]: 240,
    [Symbol(kHandle)]: TCP {
      reading: true,
      onconnection: null,
      _consumed: true,
      [Symbol(owner_symbol)]: [Circular *1]
    },
```

**Comment by irishjack490** [comment]
I made some tweaks on the requireOwnership function. but now it is telling me I don't have the right token, which I do.. I tripledchecked and it is correct.. well at least I got that.. I'll keep trying to make it work

**Comment by irishjack490** [comment]
I did some console logs to confirm I am deleting the right order from the right user and ensure I have the right token but it keeps telling me the token is not correct.. :((
```
equest User ID: new ObjectId("65cb7fe3825b95a713192701")
Resource Owner ID: {
  _id: new ObjectId("65cb7fe3825b95a713192701"),
  email: 'abc@abc.com',
  createdAt: 2024-02-13T14:42:43.686Z,
  updatedAt: 2024-02-13T23:32:38.709Z,
  __v: 0,
  token: '1e8f63a406fe9820981b572e9908d485'
}
Request User ID: new ObjectId("65cb7fe3825b95a713192701")
Resource User ID: {
  _id: new ObjectId("65cb7fe3825b95a713192701"),
  email: 'abc@abc.com',
  createdAt: 2024-02-13T14:42:43.686Z,
  updatedAt: 2024-02-13T23:32:38.709Z,
  __v: 0,
  token: '1e8f63a406fe9820981b572e9908d485'
}

 17:55:46 GMT-0600 (Central Standard Time):
OwnershipError: The provided token does not match the owner of this document
    at requireOwnership (/home/irishjack/sei/projects/Project4/DonutShopApp/DonutsAPI/lib/custom_errors.js:51:15)
    at /home/irishjack/sei/projects/Project4/DonutShopApp/DonutsAPI/app/routes/order_routes.js:92:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by nayaba** [comment]
Could you screenshot what your postman request looks like, specifically the part where you are adding the token?

**Comment by timmshinbone** [comment]
- "I made some tweaks on the requireOwnership function" -
I need to see the code after you tweaked this function. Also, why did you tweak it?

**Comment by irishjack490** [comment]
When I had the original function, it seems like it was confusing the orderId form the database with the ownerId for some reason 
Here is what I modified it to (my apologies if I wasn't supposed to do that)
```
const requireOwnership = (requestObject, resource) => {
    // Extract the user ID from the resource
    const userId = resource.user;

    console.log('Request User ID:', requestObject.user._id);
    console.log('Resource User ID:', userId);

    // Check if the authenticated user is the owner of the resource
    if (!requestObject.user._id.equals(userId)) {
        throw new OwnershipError();
    }
};
```
Here is what I get when I try the route, I put the userId, then the orderId, I made generated a fresh token right now and made sure it was in there 
![image](https://github.com/sei-ec-remote/project-4-issues/assets/146676274/2ed1db62-9670-4bec-b27e-69fe6657b349)

I appreciate your help so much

**Comment by irishjack490** [comment]
Just in case this is what I have in my route: 
```
router.delete('/orders/delete-order/:userId/:orderId', requireToken, (req, res, next) => {
    const orderId = req.params.orderId;
	
    Order.findById(orderId)
		.populate('user')
        .then(handle404)
        .then((order) => {
			console.log('Request User ID:', req.user._id)
            console.log('Resource Owner ID:', order.user);
            
            requireOwnership(req, order);

            return order.deleteOne(); 
        })
        .then(() => {
            res.sendStatus(204);
        })
        .catch(next);
});
```

**Comment by timmshinbone** [comment]
What was the idea behind those changes to requireOwnership? If you have a good reason for needing to change it, I'm open to it, it's no problem, but like, it works as long as the owner field is on the model

**Comment by timmshinbone** [comment]
Change it back to this, and share what error messages you're receiving when you try running the route:

```js
// `requestObject` should be the actual `req` object from the route file
const requireOwnership = (requestObject, resource) => {
	// `requestObject.user` will be defined in any route that uses `requireToken`
	// `requireToken` MUST be passed to the route as a second argument
	const owner = resource.owner._id ? resource.owner._id : resource.owner
	//  check if the resource.owner is an object in case populate is being used
	//  if it is, use the `_id` property and if not, just use its value
	if (!requestObject.user._id.equals(owner)) {
		throw new OwnershipError()
	}
}
```

**Comment by timmshinbone** [comment]
Trying a new approach to the orders objects
