### ISSUE TITLE
Error 500 Postman in Models/Routes

### ISSUE THREAD

**Issue by lyee197** [sei-ec-remote/project-4-issues#34]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
Creating my Models/Routes and when using postman, I receive an error 500 internal server error for my event route

### Post any code you think might be relevant (one fenced block per file)
```js
const mongoose = require('mongoose')
const commentSchema = require('./comment')
const petSchema = require('./pet')

const eventSchema = new mongoose.Schema(
	{
		name: {
			type: String,
			required: true,
		},
		description: {
			type: String,
			required: true,
		},
		date: {
			type: Date,
			required: true,
		},
		event_type: {
			type: String,
			required: true,
			
		},
		attendies: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'Pet'
		},
		owner: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
		},
		comments: {
			type: [commentSchema]
		}
	},
	{
		timestamps: true,
	}
)

module.exports = mongoose.model('Event', eventSchema)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
```
TypeError: Cannot set properties of undefined (setting 'owner')
```

### What is your best guess as to the source of the problem?
I believe the problem lies in my event models

### What things have you already tried to solve the problem?
Looking up how to set up models and asking a friend.

**Paste a link to your repository here**
[Project-4](https://github.com/lyee197/project-4)

**Comment by timmshinbone** [comment]
show the controller responsible for creating an event

**Comment by lyee197** [comment]
```js
// CREATE
// POST /events
router.post('/events', requireToken, (req, res, next) => {
	// set owner of new event to be current user
	req.body.event.owner = req.user.id
	console.log(req.body.event.owner)
	Event.create(req.body.event)
		// respond to succesful `create` with status 201 and JSON of new "event"
		.then((event) => {
			res.status(201).json({ event: event.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})
```

```
 15:20:37 GMT-0400 (Eastern Daylight Time):
TypeError: Cannot set properties of undefined (setting 'owner')
    at C:\Users\liams\sei\projects\project-4\app\routes\event_routes.js:62:23
    at Layer.handle [as handle_request] (C:\Users\liams\sei\projects\project-4\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\liams\sei\projects\project-4\node_modules\express\lib\router\route.js:137:13)
    at complete (C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\middleware\authenticate.js:262:13)
    at C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\middleware\authenticate.js:269:15
    at pass (C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\authenticator.js:428:14)
    at Authenticator.transformAuthInfo (C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\authenticator.js:450:5)
    at C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\middleware\authenticate.js:266:22
    at IncomingMessage.req.login.req.logIn (C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\http\request.js:45:13)
    at Strategy.strategy.success (C:\Users\liams\sei\projects\project-4\node_modules\passport\lib\middleware\authenticate.js:247:13)
```

I wasn't quite sure what you meant by controller response

**Comment by timmshinbone** [comment]
ok now share the json body that you're sending to the request

**Comment by lyee197** [comment]
I apologize, I found out the problem. I didn't have my Event set to anything. After I had set where I was putting my data at, it assigned the data to the object.(I don't know if I had the right terminology)

#### What I had:
```
{
     "name": "puppy play",
    "description": "Let's get all the pups out there and have a puppy party!",
    "date": "2022-5-13",
    "event_type": "public"
}
```
#### What I changed:
```
{
    "event": {
        "name": "puppy play",
        "description": "Let's get all the pups out there and have a puppy party!",
        "date": "2022-5-13",
        "event_type": "public"
    }
}
```

I believe that was the problem and the solution?

**Comment by timmshinbone** [comment]
YES! Nice work!
