### ISSUE TITLE
Attempting to 'makemigrations' for Take model

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-4-issues#46]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DTP(django, template, python) I think that's the right stack

### What's the problem you're trying to solve?
I was trying to establish a many to many relationship between my Event model and my Take model, similar to cats and cattoys

### Post any code you think might be relevant (one fenced block per file)
```py
class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.CharField(max_length=250)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    takes = models.ManyToManyField(Take)

    def __str__(self):
        return self.title

class Take(models.Model):
    opinion = models.CharField(max_length=200)

    def __str__(self):
        return self.opinion
    
    def get_absolute_url(self):
        return reverse('takes_detail', kwargs={'take_id': self.id})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
`Traceback (most recent call last):
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/manage.py", line 21, in <module>
    main()
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/FrostyAusty/.local/share/virtualenvs/django-env-FT_-x6P2/lib/python3.9/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/main_app/models.py", line 6, in <module>
    class Event(models.Model):
  File "/Users/FrostyAusty/sei/django-env/CP-TakeItOrLeaveIt/TakeItOrLeaveIt/main_app/models.py", line 17, in Event
    takes = models.ManyToManyField(Take)
NameError: name 'Take' is not defined
`

### What is your best guess as to the source of the problem?
I actually have no guess, as I don't have to import the Take model as I'm within the models.py folder and I already made a previous migration to create the Take model. I am uncertain as to why it's being read as not defined.

### What things have you already tried to solve the problem?
I have referred back to documentation and checked my files both seem correct as well. 

**Paste a link to your repository here**
https://github.com/thefrostyausty/CP-TakeItOrLeaveIt
![Screen Shot 2022-04-27 at 11 59 07 AM (2)](https://user-images.githubusercontent.com/98559337/165561343-d02b7047-31b3-4dca-84b9-1f951eb55547.png)
<img width="2240" alt="Screen Shot 2022-04-27 at 11 59 07 AM" src="https://user-images.githubusercontent.com/98559337/165561348-1cb4b749-2a6e-4381-ae58-8f1941375f48.png">

**Comment by thefrostyausty** [comment]
I am fine with waiting until after lunch to solve this 😂

**Comment by DoireannJane** [comment]
Have you put your Take above your Event model?

**Comment by thefrostyausty** [comment]
That worked thank you Doire!
