### ISSUE TITLE
production environment is running instead of development using django template

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/project-4-issues#6]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)

DR

### What's the problem you're trying to solve?

I set my .env to development, but it is still trying to run prod

### Post any code you think might be relevant (one fenced block per file)
.env
```
ENV=development
DB_NAME_DEV=composting-mgmt-systems
SECRET=lkmqc9-cbm0ut5le)-&hdv)g^l%70+$5va%upfw%2=ybqnj&m5
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
'''
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidnierman/sei/projects/composting-mgmt-systems-api/manage.py", line 21, in <module>
    main()
  File "/Users/davidnierman/sei/projects/composting-mgmt-systems-api/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/core/management/base.py", line 341, in run_from_argv
    connections.close_all()
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/db/utils.py", line 225, in close_all
    for alias in self:
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/db/utils.py", line 219, in __iter__
    return iter(self.databases)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/db/utils.py", line 153, in databases
    self._databases = settings.DATABASES
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/davidnierman/.local/share/virtualenvs/django-env-e463R511/lib/python3.9/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/davidnierman/sei/projects/composting-mgmt-systems-api/composting-mgmt-systems/settings.py", line 15, in <module>
    import dj_database_url
ModuleNotFoundError: No module named 'dj_database_url'
'''

### What is your best guess as to the source of the problem?

Somehow my .env file is not loading...

### What things have you already tried to solve the problem?
1. tried changing the value in my .env to a string using quotes 
2. tried using print() in settings file to see what is loading/being imported from .env file (nothing printed...)

**Paste a link to your repository here**
[composting-mgmt-systems-api](https://github.com/dnierman0920/composting-mgmt-systems-api)

**Comment by DoireannJane** [comment]
Are you using environ?

**Comment by DoireannJane** [comment]
Timm also suggested dotenv: [https://stackoverflow.com/questions/62925571/how-do-i-use-env-in-django]

**Comment by DoireannJane** [comment]
I believe there's an example in the boilerplate! let us know how it goes.

**Comment by rsm-dnierman** [comment]
I figured it out. I installed dotenv in my project repo and not my env
