### ISSUE TITLE
Can't create multiple happy hours with the same name

### ISSUE THREAD

**Issue by patrickga94** [sei-ec-remote/project-4-issues#74]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
My create route won't allow me to have more than one happy hour with the same name

### Post any code you think might be relevant (one fenced block per file)
```
const mongoose = require('mongoose')
const commentSchema = require('./comments')
const tagSchema = require('./tags')
const User = require('./users')
const { Schema } = mongoose

const happyHourSchema = new mongoose.Schema(
	{
		name: {
			type: String,
			required: true
		},
		address: {
			type: String,
			required: true,
		},
        city: {
            type: String,
            required: true
        },
		state: {
			type: String,
			required: true
		},
        deals: {
            type: String,
            required: true
        },
        owner: {
            type: Schema.Types.ObjectId,
            ref: 'User'
        },
        days: [{type: String, required: true}],
        startTime: {
			type: String,
			required: true
		},
		endTime: {
			type: String,
			required: true
		},
        comments: [commentSchema],
        tags: [tagSchema]

	},
	{
		timestamps: true
	}
)

module.exports = mongoose.model('HappyHour', happyHourSchema)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
MongoServerError: E11000 duplicate key error collection: happy-hours-development.happyhours index: name_1 dup key: { name: "Dollar Oysters" }
    at /home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/operations/insert.js:51:33
    at /home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/cmap/connection_pool.js:272:25
    at handleOperationResult (/home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/sdam/server.js:370:9)
    at MessageStream.messageHandler (/home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/cmap/connection.js:479:9)
    at MessageStream.emit (events.js:400:28)
    at processIncomingData (/home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
    at MessageStream._write (/home/patrickalvarez/sei/projects/project-4/Happy-houR-api/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22) {
  index: 0,
  code: 11000,
  keyPattern: { name: 1 },
  keyValue: { name: 'Dollar Oysters' }
}

### What is your best guess as to the source of the problem?
I had put unique: true in the model by accident but even after removing it it won't let me have a duplicate. Maybe I need to drop the database? Not sure

### What things have you already tried to solve the problem?
Removed the unique validator 

**Paste a link to your repository here**
https://github.com/patrickga94/Happy-houR-api/tree/dev

**Comment by patrickga94** [comment]
Ok yeah dropping the database fixed it!
