### ISSUE TITLE
unable to create a character and user during sign up

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/project-4-issues#82]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
mern

### What's the problem you're trying to solve?
trying to create a character before a user 

### Post any code you think might be relevant (one fenced block per file)
```
// SIGN UP
// POST /sign-up
router.post('/sign-up', (req, res, next) => {
	// start a promise chain, so that any errors will pass to `handle`
	const newUser = Promise.resolve(req.body.credentials)
		// reject any requests where `credentials.password` is not present, or where
		// the password is an empty string
		.then((credentials) => {
			if (
				!credentials ||
				!credentials.password ||
				credentials.password !== credentials.password_confirmation
			) {
				throw new BadParamsError()
			}
		})
		// generate a hash from the provided password, returning a promise
		.then(() => bcrypt.hash(req.body.credentials.password, bcryptSaltRounds))
		.then((hash) => {
			// return necessary params to create a user
			return {
				email: req.body.credentials.email,
				hashedPassword: hash,
			}
		})
		// create user with provided email and hashed password
		.then((user) => User.create(user))
		// send the new user object back with status 201, but `hashedPassword`
		.then( user => {
			return user
		})
		// won't be send because of the `transform` in the User model
		// pass any errors along to the error handler
		.catch(next)
		const newCharacter = Character.create(req.body.character)
	
			.then( character => {
				return character
			})
			// if an error occurs, pass it to the error handler
			.catch(next)
	
			Promise.all([newUser, newCharacter])
				.then( responseData => {
					const user = responseData[0]
					const emptyCharacter = responseData[1]
					emptyCharacter.owner = user._id
					console.log('response data - user', user)
					console.log('response data - emtpy order', emptyCharacter)
					return emptyCharacter.save()
				})
				.then((responseData) => res.status(201).json({ responseData: responseData.toObject() }))
				.catch(next)

})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
MongoServerError: E11000 duplicate key error collection: chore-api-development.characters index: owner_1 dup key: { owner: null }
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\operations\insert.js:51:33
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\cmap\connection_pool.js:272:25
    at handleOperationResult (C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\sdam\server.js:370:9)
    at MessageStream.messageHandler (C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\cmap\connection.js:479:9)
    at MessageStream.emit (node:events:390:28)
    at processIncomingData (C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\cmap\message_stream.js:108:16)
    at MessageStream._write (C:\Users\sanch\sei\actual-projects\project4\capstone-api\node_modules\mongodb\lib\cmap\message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10) {
  index: 0,
  code: 11000,
  keyPattern: { owner: 1 },
  keyValue: { owner: null }
}
TypeError: Cannot set properties of undefined (setting 'owner')
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\app\routes\user_routes.js:46:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
BadParamsError: A required parameter was omitted or invalid
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\app\routes\user_routes.js:61:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot set properties of undefined (setting 'owner')
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\app\routes\user_routes.js:46:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
BadParamsError: A required parameter was omitted or invalid
    at C:\Users\sanch\sei\actual-projects\project4\capstone-api\app\routes\user_routes.js:61:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

as well as a 500 status code on trying to make a new user

### What is your best guess as to the source of the problem?
we might need to take out the promise all and do .thens instead but we're not really sure how to go about that

### What things have you already tried to solve the problem?
tried googling the errors and switching around the order of the promises in the route but not really getting anywhere

**Paste a link to your repository here**
https://github.com/jscodeguy/capstone-api

**Comment by jscodeguy** [comment]
we've gotten rid of the promise.all and started adding more promises but we're getting the same errors on making a new character

**Comment by jscodeguy** [comment]
the promise chain we made 
```Character.create(req.body.character)
		.then(createdCharacter => {
			Promise.resolve(req.body.credentials)
			.then((credentials) => {
				if (
					!credentials ||
					!credentials.password ||
					credentials.password !== credentials.password_confirmation
				) {
					throw new BadParamsError()
				}
			})
			.then(() => bcrypt.hash(req.body.credentials.password, bcryptSaltRounds))
			.then((hash) => {
				// return necessary params to create a user
				return {
					email: req.body.credentials.email,
					hashedPassword: hash,
				}
			})
			.then(credentials)
			User.create({credentials})
			.then(resp => {
				console.log(resp)
			})
		})
		.then(res => {
			const user = responseData[0]
			const emptyCharacter = responseData[1]
			emptyCharacter.owner = user._id
			console.log('response data - user', user)
			console.log('response data - emtpy order', emptyCharacter)
			return emptyCharacter.save()
		})
	.catch(err => console.log('this is err in user_routes', err))```
