### ISSUE TITLE
issue with access profile show route

### ISSUE THREAD

**Issue by clds84** [sei-ec-remote/project-4-issues#83]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
MERN

### What's the problem you're trying to solve?
I'm successfully able to create and show in Postman, and I'm able to create in the app front end, but when I try to click on Profile in the nav bar, I get this error: `xhr.js:210          GET http://localhost:8000/profile/:id 422 (Unprocessable Entity)`

### Post any code you think might be relevant (one fenced block per file)
this is my api/profile route. One thing to note is when doing the project axios calls, where export const getProject(projectId), I'm able to console log projectId and obtain the ID but in this case with the profile, it's undefined. I'm wondering if it has to do with some little difference in code bc there's no index in this case. It's just straight to show, and otherwise create. I'm thinking about how when you have say cards for the index, you click on the card and that takes you to the show route, retrieving its id in the process. So maybe there's something I'm missing in terms of when you click on the profile in nav bar and expect to have the ID. 

```js
import apiUrl from '../apiConfig'
import axios from 'axios'

export const getProfile = (profileId) => {
    console.log('this is profileId',profileId)
    return axios(`${apiUrl}/profile/${profileId}`)
}
// POST -> create function for profile
export const createProfile = (user, newProfile) => {
    console.log('user', user)
    console.log('this is new Project ', newProfile)
    return axios({
        url: `${apiUrl}/profile`,
        method: 'POST',
        header: {
            Authorization:`Token token=${user.token}`
        },
        data: { profile:{ 
            owner:user._id,
            name: newProfile.name,
            about: newProfile.about,
            sewingBackground:  newProfile.sewingBackground,
            machineType: newProfile.machineType,
            preferredNotions: newProfile.preferredNotions,
            projectBucketlist: newProfile.projectBucketlist,
        }}
    })
}


    
```

This is my ShowProfile component
```js
import React, { useState, useEffect } from 'react'
import { Button, Card, Container } from 'react-bootstrap'
import { Link } from 'react-router-dom'
import { getProfile } from '../../api/profile'
import { useParams, useNavigate } from 'react-router-dom'

const ShowProfile = (props) => {
    console.log('these are the props in profile', props)
    const [profile, setProfile] = useState(null)
    const { user, msgAlert } = props
    const { id } = useParams()
    
    console.log('this is id', id)
    useEffect(() => {
        getProfile(id)
            .then(profile => {
                console.log('this is the profile data', profile.data.profile)
                setProfile(profile.data.profile)
                console.log('this is profile',profile)
            })
            .catch(() =>
            msgAlert({
                heading: 'Oh No!',
                message: 'shit',
                variant: 'danger',
        }))
    }, [])

    if(!profile) {
        return (
            <>
                <h2>Looks like you don't have a profile yet! Click <Link to='/addProfile'>here</Link> to get started</h2>
            </>
        )
    }
    if (profile) {
        return (
            <Container className="justify-content-center">
                <Card  style={{ width: '30%' }} className="m-2" >
                    <Card.Header>{profile.name} </Card.Header>
                    <Card.Body>
                        <Card.Text>
                            {/* <Link to={`/projects/${profile._id}`}>View </Link> */}
                        </Card.Text>
                    </Card.Body>
                </Card>
            </Container>
        )
    }
}
//key={profile.id} this is on 39, <Card ()>
export default ShowProfile
```

This is my backend stuff:

```js
// Express docs: http://expressjs.com/en/api.html
const express = require('express')
// Passport docs: http://www.passportjs.org/docs/
const passport = require('passport')

// pull in Mongoose model for profiles
const Profile = require('../models/profile')

// this is a collection of methods that help us detect situations when we need
// to throw a custom error
const customErrors = require('../../lib/custom_errors')

// we'll use this function to send 404 when non-existant document is requested
const handle404 = customErrors.handle404
// we'll use this function to send 401 when a user tries to modify a resource
// that's owned by someone else
const requireOwnership = customErrors.requireOwnership

// this is middleware that will remove blank fields from `req.body`, e.g.
// { profile: { title: '', text: 'foo' } } -> { profile: { text: 'foo' } }
const removeBlanks = require('../../lib/remove_blank_fields')
const profile = require('../models/profile')
// passing this as a second argument to `router.<verb>` will make it
// so that a token MUST be passed for that route to be available
// it will also set `req.user`
const requireToken = passport.authenticate('bearer', { session: false })

// instantiate a router (mini app that only handles routes)
const router = express.Router()

// INDEX
// GET /profile 
//
router.get('/profile', requireToken, (req, res, next) => {
	Profile.find()
		.then((profiles) => {
			// `profiles` will be an array of Mongoose documents
			// we want to convert each one to a POJO, so we use `.map` to
			// apply `.toObject` to each one
			return profiles.map((profile) => profile.toObject())
		})
		// respond with status 200 and JSON of the profiles
		.then((profiles) => res.status(200).json({ profiles: profiles }))
		// if an error occurs, pass it to the handler
		.catch(next)
})
// SHOW
// GET /profiles/6265525bd078af1d97610e32
router.get('/profile/:id', (req, res, next) => {
	
	// req.params.id will be set based on the `:id` in the route
	Profile.findById(req.params.id)
		.then(handle404)
		// if `findById` is succesful, respond with 200 and "profile" JSON
		.then((profile) => res.status(200).json({ profile: profile.toObject() }))
		// if an error occurs, pass it to the handler
		.catch(next)
})
// CREATE
// POST /profiles
router.post('/profile',(req, res, next) => {
	// set owner of new profile to be current user
	//req.body.profile.owner = req.user.id

	Profile.create(req.body.profile)
		// respond to succesful `create` with status 201 and JSON of new "profile"
		.then((profile) => {
			res.status(201).json({ profile: profile.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})
// UPDATE
// PATCH /profiles/5a7db6c74d55bc51bdf39793
//
router.patch('/profile/:id', requireToken, removeBlanks, (req, res, next) => {
	// if the client attempts to change the `owner` property by including a new
	// owner, prevent that by deleting that key/value pair
	delete req.body.profile.owner

	Profile.findById(req.params.id)
		.then(handle404)
		.then((profile) => {
			// pass the `req` object and the Mongoose record to `requireOwnership`
			// it will throw an error if the current user isn't the owner
			requireOwnership(req, profile)

			// pass the result of Mongoose's `.update` to the next `.then`
			return profile.updateOne(req.body.profile)
		})
		// if that succeeded, return 204 and no JSON
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
// DESTROY
// DELETE /profile/626574ae4df379dfeecf3773
router.delete('/profile/:id', requireToken, (req, res, next) => {
	profile.findById(req.params.id)
		.then(handle404)
		.then((profile) => {
			// throw an error if current user doesn't own `profile`
			requireOwnership(req, profile)
			// delete the profile ONLY IF the above didn't throw
			profile.deleteOne()
		})
		// send back 204 and no content if the deletion succeeded
		.then(() => res.sendStatus(204))
		// if an error occurs, pass it to the handler
		.catch(next)
})
module.exports = router
```

This is the authenticated header bit:

```js
const authenticatedOptions = (
	<>
		<Nav.Item className="m-2">
			<Link to='change-password' style={linkStyle}>
				Change Password
			</Link>
		</Nav.Item>
		<Nav.Item className="m-2">
			<Link to='sign-out' style={linkStyle}>
				Sign Out
			</Link>
		</Nav.Item>
		<Nav.Item className="m-2">
			<Link to='/tutorials' style={linkStyle}>
				Tutorials
			</Link>
		</Nav.Item>
		<Nav.Item className="m-2">
			<Link to='/profile/:id' style={linkStyle}>
				Profile
			</Link>
			
		</Nav.Item>
		<Nav.Item className="m-2">
			<Link to='/community-Space' style={linkStyle}>
				Community Space
			</Link>
		</Nav.Item>
		<Nav.Item className="m-2">
			<Link to='/projects' style={linkStyle}>
				My Projects
			</Link>
		</Nav.Item>

	</>
)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

This is in the CLI:

```
==== Incoming Request =====

Fri Apr 29 2022 14:40:20 GMT-0400 (Eastern Daylight Time)
GET /profile/:id
body {}

============================


 14:40:21 GMT-0400 (Eastern Daylight Time):
CastError: Cast to ObjectId failed for value ":id" (type string) at path "_id" for model "Profile"
    at model.Query.exec (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/query.js:4584:21)
    at model.Query.Query.then (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/query.js:4683:15)
    at /Users/cristian/sei/projects/project-4/API/Sewing-API/app/routes/profile_routes.js:53:4
    at Layer.handle [as handle_request] (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/layer.js:95:5)
    at /Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/index.js:281:22
    at param (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/express/lib/router/index.js:365:14) {
  messageFormat: undefined,
  stringValue: '":id"',
  kind: 'ObjectId',
  value: ':id',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
      at new BSONTypeError (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/bson/lib/error.js:41:28)
      at new ObjectId (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/bson/lib/objectid.js:65:23)
      at castObjectId (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/schema/objectid.js:245:12)
      at ObjectId.SchemaType.applySetters (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/schematype.js:1135:12)
      at ObjectId.SchemaType._castForQuery (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/schematype.js:1567:15)
      at ObjectId.SchemaType.castForQuery (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/schematype.js:1557:15)
      at ObjectId.SchemaType.castForQueryWrapper (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/schematype.js:1534:20)
      at cast (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/cast.js:336:32)
      at model.Query.Query.cast (/Users/cristian/sei/projects/project-4/API/Sewing-API/node_modules/mongoose/lib/query.js:5007:12),
  valueType: 'string'
}

```

This is in the console:

```
xhr.js:210          GET http://localhost:8000/profile/:id 422 (Unprocessable Entity)
```

### What is your best guess as to the source of the problem?

I think the axios call is a clue that the show axios call for the profile is coming up with an undefined parameter of profileId, so http://localhost8000/profile/${profileId} isn't doing anything
### What things have you already tried to solve the problem?
I've tried playing with the req.body for the create, I've tried playing with the backend and trying a few different things, and I can't seem to figure out how to attack this bug. 

**Paste a link to your repository here**

**Comment by tkolsrud** [comment]
Issue was with `useParams` implementation, pivoted to using currentuser instead
