### ISSUE TITLE
error creating vehicle

### ISSUE THREAD

**Issue by jadenRuplal** [sei-ec-remote/project-4-issues#89]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
express react

### What's the problem you're trying to solve?
I'm getting an error on the API side when creating a listing that I think will cause problems in the future

### Post any code you think might be relevant (one fenced block per file)
```
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
10:09:19 GMT-0400 (Eastern Daylight Time):
CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "Car"
    at model.Query.exec (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/query.js:4584:21)
    at model.Query.Query.then (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/query.js:4683:15)
    at /Users/jadenruplal/sei/projects/project4/project-4-carbid-api/app/routes/car_routes.js:51:4
    at Layer.handle [as handle_request] (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/index.js:281:22
    at param (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/express/lib/router/index.js:365:14) {
  messageFormat: undefined,
  stringValue: '"undefined"',
  kind: 'ObjectId',
  value: 'undefined',
  path: '_id',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters
      at new BSONTypeError (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/bson/lib/error.js:41:28)
      at new ObjectId (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/bson/lib/objectid.js:65:23)
      at castObjectId (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/schema/objectid.js:245:12)
      at ObjectId.SchemaType.applySetters (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/schematype.js:1135:12)
      at ObjectId.SchemaType._castForQuery (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/schematype.js:1567:15)
      at ObjectId.SchemaType.castForQuery (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/schematype.js:1557:15)
      at ObjectId.SchemaType.castForQueryWrapper (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/schematype.js:1534:20)
      at cast (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/cast.js:336:32)
      at model.Query.Query.cast (/Users/jadenruplal/sei/projects/project4/project-4-carbid-api/node_modules/mongoose/lib/query.js:5007:12),
  valueType: 'string'
}

### What is your best guess as to the source of the problem?
not sure but it does create the object even with this error

### What things have you already tried to solve the problem?

**Paste a link to your repository here**
https://github.com/jadenRuplal/project-4-carbid-api
https://github.com/jadenRuplal/project-4-carbid-client

**Comment by kestler01** [comment]
definitely share up the route in a code block 
also the request from postman

**Comment by jadenRuplal** [comment]
form to create
`const CarForm = (props) => {
    const { car, handleChange, handleSubmit, heading } = props

    return (
        <Container className="justify-content-center">
            <h3>{heading}</h3>
            <Form onSubmit={handleSubmit}>
                <Form.Label htmlFor="make">Make</Form.Label>
                <Form.Control
                    placeholder="What is this cars make?"
                    name="make"
                    id="make"
                    value={car.make}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="model">Model</Form.Label>
                <Form.Control
                    placeholder="What is the cars name?"
                    name="model"
                    id="model"
                    value={car.model}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="year">Year</Form.Label>
                <Form.Control
                    placeholder="Enter the cars year"
                    type="number"
                    name="year"
                    id="year"
                    value={car.year}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="image">Image</Form.Label>
                <Form.Control
                    placeholder="Image URL"
                    name="image"
                    id="image"
                    value={car.image}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="type">Type</Form.Label>
                <Form.Control
                    placeholder="Whats the class of the car? EX(sedan)"
                    name="type"
                    id="type"
                    value={car.type}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="description">Description</Form.Label>
                <Form.Control
                    placeholder="Give a brief description"
                    name="description"
                    id="description"
                    value={car.description}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="starting price">Starting price</Form.Label>
                <Form.Control
                    placeholder="Enter the cars starting bid"
                    type="number"
                    name="startingbid"
                    id="startingbid"
                    value={car.startingbid}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="buyout">Buynow</Form.Label>
                <Form.Control
                    placeholder="Enter the cars max price"
                    type="number"
                    name="buyout"
                    id="buyout"
                    value={car.buyout}
                    onChange={handleChange}
                />
                <Form.Label htmlFor="stock">Stock</Form.Label>
                <Form.Control
                    placeholder="How many you got?"
                    name="stock"
                    id="stock"
                    value={car.stock}
                    onChange={handleChange}
                />
                <Button type="submit">Submit</Button>
            </Form>
        </Container>
    )
}

export default CarForm`



Api route
`// CREATE
// POST /cars
router.post('/cars', requireToken, (req, res, next) => {
	// set owner of new car to be current user
	req.body.car.owner = req.user.id

	Car.create(req.body.car)
		// respond to succesful `create` with status 201 and JSON of new "car"
		.then((car) => {
			res.status(201).json({ car: car.toObject() })
		})
		// if an error occurs, pass it off to our error handler
		// the error handler needs the error message and the `res` object so that it
		// can send an error message back to the client
		.catch(next)
})`


Client API 
`export const createCar = (user, newCar) => {

    return axios({
        url: apiUrl + '/cars',
        method: 'POST',
        headers: {
            Authorization: `Token token=${user.token}`,
        },
        data: { car: newCar }
    })
}`

**Comment by jadenRuplal** [comment]
i didn't use postman to test routes

**Comment by kestler01** [comment]
what does your request look like

**Comment by jadenRuplal** [comment]
its either this 
Mon Aug 22 2022 10:09:19 GMT-0400 (Eastern Daylight Time)
GET /cars
body {}

or nothing but the object is still created correctly

**Comment by jadenRuplal** [comment]
can we go into a breakout room? i think its better to visually see it

**Comment by kestler01** [comment]
room 25
