### ISSUE TITLE
Getting a modulenotfound error after reinstalling django_auth_template

### ISSUE THREAD

**Issue by alysarnau** [sei-ec-remote/project-4-issues#93]
###### (ex: MERN(mongoose + react), DR(django + react), PEN, etc.)
DR stack

### What's the problem you're trying to solve?
Had to reinstall the django-auth-template and now it's giving me a PHANTOM `ModuleNotFoundError: No module named 'django_auth_template'`

### Post any code you think might be relevant (one fenced block per file)
```
I've gone through the whole damn codebase and it's not there.
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

'''
(myJunimoAPI) alys@Alys-Volatile:~/sei_ice_pops/projects/StardewValleyHelper/myJunimoAPI$ python manage.py runserver
Traceback (most recent call last):
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 81, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_auth_template'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/core/management/base.py", line 415, in run_from_argv
    connections.close_all()
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/connection.py", line 84, in close_all
    for conn in self.all(initialized_only=True):
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/connection.py", line 76, in all
    return [
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/db/utils.py", line 148, in configure_settings
    databases = super().configure_settings(databases)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/alys/.local/share/virtualenvs/myJunimoAPI-_DeNEuEc/lib/python3.8/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_auth_template'

'''
### What is your best guess as to the source of the problem?
That there's a faulty reference SOMEWHERE

### What things have you already tried to solve the problem?
gone through the whole codebase with the search function to try and find the missing module reference

**Paste a link to your repository here**
https://github.com/alysvolatile/my-junimo-api (I'm on the reinstall branch)

**Comment by alysarnau** [comment]
AS EXPECTED, AS SOON AS I WROTE IT ALL OUT I FIGURED IT OUT.

I JUST HAD TO SAVE THE FILE, WHERE I HAD ALREADY DELETED THE REFERENCE, BUT I HAD NOT SAVED IT.
